<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Trade.Gateway.Api.Contract</RootNamespace>
    <IsPackable>true</IsPackable>
    <PackageId>Defra.Trade.Gateway.Api.Contract</PackageId>
    <VersionPrefix>0.1.0</VersionPrefix>
    <PackageDescription>Defra Trade Gateway Api Contracts</PackageDescription>
    <Company>DEFRA</Company>
    <RepositoryUrl>https://github.com/DEFRA/trade-gateway</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>
</Project>
