//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/ched/v06")]
    public partial class ChedCRFLRequestType
    {
        private CompetentCustomsOfficeType competentCustomsOfficeField;
        private CRFLMSFilters4CHEDEnhancedType cRFLMSFilters4CHEDField;
        private CRFLMSFilters4DateTimeRangeType cRFLMSFilters4DateTimeRangeField;
        private CRFLCHEDFilters4ConsignmentType cRFLCHEDFilters4ConsignmentField;
        private System.DateTime sendingDateField;
        private SubscriptionIndicationExtendedNumericalSizeType subscriptionIndicationField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CompetentCustomsOfficeType CompetentCustomsOffice
        {
            get
            {
                return this.competentCustomsOfficeField;
            }

            set
            {
                this.competentCustomsOfficeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public CRFLMSFilters4CHEDEnhancedType CRFLMSFilters4CHED
        {
            get
            {
                return this.cRFLMSFilters4CHEDField;
            }

            set
            {
                this.cRFLMSFilters4CHEDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public CRFLMSFilters4DateTimeRangeType CRFLMSFilters4DateTimeRange
        {
            get
            {
                return this.cRFLMSFilters4DateTimeRangeField;
            }

            set
            {
                this.cRFLMSFilters4DateTimeRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public CRFLCHEDFilters4ConsignmentType CRFLCHEDFilters4Consignment
        {
            get
            {
                return this.cRFLCHEDFilters4ConsignmentField;
            }

            set
            {
                this.cRFLCHEDFilters4ConsignmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public System.DateTime SendingDate
        {
            get
            {
                return this.sendingDateField;
            }

            set
            {
                this.sendingDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public SubscriptionIndicationExtendedNumericalSizeType SubscriptionIndication
        {
            get
            {
                return this.subscriptionIndicationField;
            }

            set
            {
                this.subscriptionIndicationField = value;
            }
        }
    }
}