//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/certificate/ched/v2")]
    public partial class FindChedCertificateRequestType
    {
        private CodeType[] typeField;
        private StatusCodeType[] statusField;
        private CodeType purposeField;
        private bool transshippedField;
        private bool transshippedFieldSpecified;
        private bool transferField;
        private bool transferFieldSpecified;
        private bool hasPlantHealthNonComplianceField;
        private bool hasPlantHealthNonComplianceFieldSpecified;
        private bool hasPendingLaboratoryTestsField;
        private bool hasPendingLaboratoryTestsFieldSpecified;
        private bool requiresFollowUpField;
        private bool requiresFollowUpFieldSpecified;
        private bool isDigitallySignedField;
        private bool isDigitallySignedFieldSpecified;
        private IDType localReferenceField;
        private IDType phytoReferenceField;
        private IDType phytoLocalReferenceField;
        private CNCodeFilter[] cNCodeField;
        private CodeType bCPCodeOrUnLocodeField;
        private IDType countryOfIssuanceField;
        private IDType countryOfEntryField;
        private IDType countryOfDispatchField;
        private IDType countryOfOriginField;
        private IDType countryOfPlaceOfDestinationField;
        private IDType countryOfTransferControlPointField;
        private IDType countryOfConsignorField;
        private IDType countryOfConsigneeField;
        private DateTimeRange createDateTimeRangeField;
        private DateTimeRange updateDateTimeRangeField;
        private DateTimeRange statusChangeDateTimeRangeField;
        private DateTimeRange declarationDateTimeRangeField;
        private DateTimeRange decisionDateTimeRangeField;
        private DateTimeRange priorNotificationDateTimeRangeField;
        private int pageSizeField;
        private int offsetField;
        public FindChedCertificateRequestType()
        {
            this.transshippedField = true;
            this.transferField = true;
            this.hasPlantHealthNonComplianceField = true;
            this.hasPendingLaboratoryTestsField = true;
            this.requiresFollowUpField = true;
            this.isDigitallySignedField = true;
            this.pageSizeField = 100;
            this.offsetField = 0;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Type", Order = 0)]
        public CodeType[] Type
        {
            get
            {
                return this.typeField;
            }

            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Status", Order = 1)]
        public StatusCodeType[] Status
        {
            get
            {
                return this.statusField;
            }

            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public CodeType Purpose
        {
            get
            {
                return this.purposeField;
            }

            set
            {
                this.purposeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public bool Transshipped
        {
            get
            {
                return this.transshippedField;
            }

            set
            {
                this.transshippedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransshippedSpecified
        {
            get
            {
                return this.transshippedFieldSpecified;
            }

            set
            {
                this.transshippedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public bool Transfer
        {
            get
            {
                return this.transferField;
            }

            set
            {
                this.transferField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransferSpecified
        {
            get
            {
                return this.transferFieldSpecified;
            }

            set
            {
                this.transferFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public bool HasPlantHealthNonCompliance
        {
            get
            {
                return this.hasPlantHealthNonComplianceField;
            }

            set
            {
                this.hasPlantHealthNonComplianceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasPlantHealthNonComplianceSpecified
        {
            get
            {
                return this.hasPlantHealthNonComplianceFieldSpecified;
            }

            set
            {
                this.hasPlantHealthNonComplianceFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public bool HasPendingLaboratoryTests
        {
            get
            {
                return this.hasPendingLaboratoryTestsField;
            }

            set
            {
                this.hasPendingLaboratoryTestsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasPendingLaboratoryTestsSpecified
        {
            get
            {
                return this.hasPendingLaboratoryTestsFieldSpecified;
            }

            set
            {
                this.hasPendingLaboratoryTestsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public bool RequiresFollowUp
        {
            get
            {
                return this.requiresFollowUpField;
            }

            set
            {
                this.requiresFollowUpField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequiresFollowUpSpecified
        {
            get
            {
                return this.requiresFollowUpFieldSpecified;
            }

            set
            {
                this.requiresFollowUpFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public bool IsDigitallySigned
        {
            get
            {
                return this.isDigitallySignedField;
            }

            set
            {
                this.isDigitallySignedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsDigitallySignedSpecified
        {
            get
            {
                return this.isDigitallySignedFieldSpecified;
            }

            set
            {
                this.isDigitallySignedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public IDType LocalReference
        {
            get
            {
                return this.localReferenceField;
            }

            set
            {
                this.localReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public IDType PhytoReference
        {
            get
            {
                return this.phytoReferenceField;
            }

            set
            {
                this.phytoReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public IDType PhytoLocalReference
        {
            get
            {
                return this.phytoLocalReferenceField;
            }

            set
            {
                this.phytoLocalReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CNCode", Order = 12)]
        public CNCodeFilter[] CNCode
        {
            get
            {
                return this.cNCodeField;
            }

            set
            {
                this.cNCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public CodeType BCPCodeOrUnLocode
        {
            get
            {
                return this.bCPCodeOrUnLocodeField;
            }

            set
            {
                this.bCPCodeOrUnLocodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public IDType CountryOfIssuance
        {
            get
            {
                return this.countryOfIssuanceField;
            }

            set
            {
                this.countryOfIssuanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public IDType CountryOfEntry
        {
            get
            {
                return this.countryOfEntryField;
            }

            set
            {
                this.countryOfEntryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 16)]
        public IDType CountryOfDispatch
        {
            get
            {
                return this.countryOfDispatchField;
            }

            set
            {
                this.countryOfDispatchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public IDType CountryOfOrigin
        {
            get
            {
                return this.countryOfOriginField;
            }

            set
            {
                this.countryOfOriginField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public IDType CountryOfPlaceOfDestination
        {
            get
            {
                return this.countryOfPlaceOfDestinationField;
            }

            set
            {
                this.countryOfPlaceOfDestinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        public IDType CountryOfTransferControlPoint
        {
            get
            {
                return this.countryOfTransferControlPointField;
            }

            set
            {
                this.countryOfTransferControlPointField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public IDType CountryOfConsignor
        {
            get
            {
                return this.countryOfConsignorField;
            }

            set
            {
                this.countryOfConsignorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public IDType CountryOfConsignee
        {
            get
            {
                return this.countryOfConsigneeField;
            }

            set
            {
                this.countryOfConsigneeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 22)]
        public DateTimeRange CreateDateTimeRange
        {
            get
            {
                return this.createDateTimeRangeField;
            }

            set
            {
                this.createDateTimeRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 23)]
        public DateTimeRange UpdateDateTimeRange
        {
            get
            {
                return this.updateDateTimeRangeField;
            }

            set
            {
                this.updateDateTimeRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 24)]
        public DateTimeRange StatusChangeDateTimeRange
        {
            get
            {
                return this.statusChangeDateTimeRangeField;
            }

            set
            {
                this.statusChangeDateTimeRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 25)]
        public DateTimeRange DeclarationDateTimeRange
        {
            get
            {
                return this.declarationDateTimeRangeField;
            }

            set
            {
                this.declarationDateTimeRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 26)]
        public DateTimeRange DecisionDateTimeRange
        {
            get
            {
                return this.decisionDateTimeRangeField;
            }

            set
            {
                this.decisionDateTimeRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 27)]
        public DateTimeRange PriorNotificationDateTimeRange
        {
            get
            {
                return this.priorNotificationDateTimeRangeField;
            }

            set
            {
                this.priorNotificationDateTimeRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(100)]
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }

            set
            {
                this.pageSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int offset
        {
            get
            {
                return this.offsetField;
            }

            set
            {
                this.offsetField = value;
            }
        }
    }
}