//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class FindChedCertificateResponse
    {
        [System.ServiceModel.MessageBodyMemberAttribute(Name = "FindChedCertificateResponse", Namespace = "http://ec.europa.eu/tracesnt/certificate/ched/v2", Order = 0)]
        public TracesNT.WebServices.FindChedCertificateResultType FindChedCertificateResponse1;
        public FindChedCertificateResponse()
        {
        }

        public FindChedCertificateResponse(TracesNT.WebServices.FindChedCertificateResultType FindChedCertificateResponse1)
        {
            this.FindChedCertificateResponse1 = FindChedCertificateResponse1;
        }
    }
}