//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class FindDocomCertificateResponse
    {
        [System.ServiceModel.MessageBodyMemberAttribute(Name = "FindDocomCertificateResponse", Namespace = "http://ec.europa.eu/tracesnt/certificate/docom/retrieval/v1", Order = 0)]
        public TracesNT.WebServices.FindDocomCertificateResultType FindDocomCertificateResponse1;
        public FindDocomCertificateResponse()
        {
        }

        public FindDocomCertificateResponse(TracesNT.WebServices.FindDocomCertificateResultType FindDocomCertificateResponse1)
        {
            this.FindDocomCertificateResponse1 = FindDocomCertificateResponse1;
        }
    }
}