//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/certificate/euintra/v1")]
    public partial class FindEuIntraCertificateRequestType
    {
        private StatusCodeType[] statusField;
        private bool hasControlsField;
        private bool hasControlsFieldSpecified;
        private string localIDField;
        private CNCodeFilter[] cNCodeField;
        private DateTimeRange createDateTimeRangeField;
        private DateTimeRange updateDateTimeRangeField;
        private DateTimeRange statusChangeDateTimeRangeField;
        private DateTimeRange declarationDateTimeRangeField;
        private DateTimeRange certificationDateTimeRangeField;
        private DateTimeRange departureDateTimeRangeField;
        private string centralCompetentAuthorityActivityCodeField;
        private string localCompetentAuthorityActivityCodeField;
        private IDType countryOfIssuanceField;
        private IDType countryOfConsignorField;
        private IDType countryOfConsigneeField;
        private IDType countryOfAssemblyOperatorField;
        private IDType[] countryOfOriginField;
        private IDType countryOfDestinationField;
        private IDType countryOfDispatchField;
        private IDType countryOfPlaceOfLoadingField;
        private IDType countryOfTransitField;
        private IDType countryOfDestinationForExportField;
        private StringFilterType[] commodityIdentificationNumberField;
        private StringFilterType transporterIdentifierField;
        private StringFilterType meansOfTransportIdentifierField;
        private TransportModeCodeContentType meansOfTransportTypeField;
        private bool meansOfTransportTypeFieldSpecified;
        private int pageSizeField;
        private int offsetField;
        public FindEuIntraCertificateRequestType()
        {
            this.hasControlsField = true;
            this.pageSizeField = 100;
            this.offsetField = 0;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Status", Order = 0)]
        public StatusCodeType[] Status
        {
            get
            {
                return this.statusField;
            }

            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public bool HasControls
        {
            get
            {
                return this.hasControlsField;
            }

            set
            {
                this.hasControlsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasControlsSpecified
        {
            get
            {
                return this.hasControlsFieldSpecified;
            }

            set
            {
                this.hasControlsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token", Order = 2)]
        public string LocalID
        {
            get
            {
                return this.localIDField;
            }

            set
            {
                this.localIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CNCode", Order = 3)]
        public CNCodeFilter[] CNCode
        {
            get
            {
                return this.cNCodeField;
            }

            set
            {
                this.cNCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public DateTimeRange CreateDateTimeRange
        {
            get
            {
                return this.createDateTimeRangeField;
            }

            set
            {
                this.createDateTimeRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public DateTimeRange UpdateDateTimeRange
        {
            get
            {
                return this.updateDateTimeRangeField;
            }

            set
            {
                this.updateDateTimeRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public DateTimeRange StatusChangeDateTimeRange
        {
            get
            {
                return this.statusChangeDateTimeRangeField;
            }

            set
            {
                this.statusChangeDateTimeRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public DateTimeRange DeclarationDateTimeRange
        {
            get
            {
                return this.declarationDateTimeRangeField;
            }

            set
            {
                this.declarationDateTimeRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public DateTimeRange CertificationDateTimeRange
        {
            get
            {
                return this.certificationDateTimeRangeField;
            }

            set
            {
                this.certificationDateTimeRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public DateTimeRange DepartureDateTimeRange
        {
            get
            {
                return this.departureDateTimeRangeField;
            }

            set
            {
                this.departureDateTimeRangeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token", Order = 10)]
        public string CentralCompetentAuthorityActivityCode
        {
            get
            {
                return this.centralCompetentAuthorityActivityCodeField;
            }

            set
            {
                this.centralCompetentAuthorityActivityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token", Order = 11)]
        public string LocalCompetentAuthorityActivityCode
        {
            get
            {
                return this.localCompetentAuthorityActivityCodeField;
            }

            set
            {
                this.localCompetentAuthorityActivityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public IDType CountryOfIssuance
        {
            get
            {
                return this.countryOfIssuanceField;
            }

            set
            {
                this.countryOfIssuanceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public IDType CountryOfConsignor
        {
            get
            {
                return this.countryOfConsignorField;
            }

            set
            {
                this.countryOfConsignorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public IDType CountryOfConsignee
        {
            get
            {
                return this.countryOfConsigneeField;
            }

            set
            {
                this.countryOfConsigneeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public IDType CountryOfAssemblyOperator
        {
            get
            {
                return this.countryOfAssemblyOperatorField;
            }

            set
            {
                this.countryOfAssemblyOperatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CountryOfOrigin", Order = 16)]
        public IDType[] CountryOfOrigin
        {
            get
            {
                return this.countryOfOriginField;
            }

            set
            {
                this.countryOfOriginField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public IDType CountryOfDestination
        {
            get
            {
                return this.countryOfDestinationField;
            }

            set
            {
                this.countryOfDestinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public IDType CountryOfDispatch
        {
            get
            {
                return this.countryOfDispatchField;
            }

            set
            {
                this.countryOfDispatchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 19)]
        public IDType CountryOfPlaceOfLoading
        {
            get
            {
                return this.countryOfPlaceOfLoadingField;
            }

            set
            {
                this.countryOfPlaceOfLoadingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public IDType CountryOfTransit
        {
            get
            {
                return this.countryOfTransitField;
            }

            set
            {
                this.countryOfTransitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public IDType CountryOfDestinationForExport
        {
            get
            {
                return this.countryOfDestinationForExportField;
            }

            set
            {
                this.countryOfDestinationForExportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommodityIdentificationNumber", Order = 22)]
        public StringFilterType[] CommodityIdentificationNumber
        {
            get
            {
                return this.commodityIdentificationNumberField;
            }

            set
            {
                this.commodityIdentificationNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 23)]
        public StringFilterType TransporterIdentifier
        {
            get
            {
                return this.transporterIdentifierField;
            }

            set
            {
                this.transporterIdentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 24)]
        public StringFilterType MeansOfTransportIdentifier
        {
            get
            {
                return this.meansOfTransportIdentifierField;
            }

            set
            {
                this.meansOfTransportIdentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 25)]
        public TransportModeCodeContentType MeansOfTransportType
        {
            get
            {
                return this.meansOfTransportTypeField;
            }

            set
            {
                this.meansOfTransportTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MeansOfTransportTypeSpecified
        {
            get
            {
                return this.meansOfTransportTypeFieldSpecified;
            }

            set
            {
                this.meansOfTransportTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(100)]
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }

            set
            {
                this.pageSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(0)]
        public int offset
        {
            get
            {
                return this.offsetField;
            }

            set
            {
                this.offsetField = value;
            }
        }
    }
}