//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/certificate/attachments/v1")]
    public partial class GetCertificateAttachmentRequestType
    {
        private object itemField;
        private ItemChoiceType1 itemElementNameField;
        private string fileNameField;
        private long documentIdField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CertificateReference", typeof(string), DataType = "token", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("ChedCertificateReference", typeof(string), DataType = "token", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("CoiCertificateReference", typeof(CoiCertificateIdentifierType), Order = 0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public object Item
        {
            get
            {
                return this.itemField;
            }

            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }

            set
            {
                this.itemElementNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string FileName
        {
            get
            {
                return this.fileNameField;
            }

            set
            {
                this.fileNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public long DocumentId
        {
            get
            {
                return this.documentIdField;
            }

            set
            {
                this.documentIdField = value;
            }
        }
    }
}