//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetCertificateModelResponse
    {
        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/message/v1")]
        public TracesNT.WebServices.MessageType Message;
        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetCertificateModelResponse", Namespace = "http://ec.europa.eu/tracesnt/referencedata/v1", Order = 0)]
        public TracesNT.WebServices.GetCertificateModelResponseType GetCertificateModelResponse1;
        public GetCertificateModelResponse()
        {
        }

        public GetCertificateModelResponse(TracesNT.WebServices.MessageType Message, TracesNT.WebServices.GetCertificateModelResponseType GetCertificateModelResponse1)
        {
            this.Message = Message;
            this.GetCertificateModelResponse1 = GetCertificateModelResponse1;
        }
    }
}