//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/referencedata/v1")]
    public partial class GetClassificationTreeNodeDetailRequestType
    {
        private string treeIDField;
        private object itemField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token", Order = 0)]
        public string TreeID
        {
            get
            {
                return this.treeIDField;
            }

            set
            {
                this.treeIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CNCode", typeof(CodeType), Order = 1)]
        [System.Xml.Serialization.XmlElementAttribute("Path", typeof(string), DataType = "token", Order = 1)]
        public object Item
        {
            get
            {
                return this.itemField;
            }

            set
            {
                this.itemField = value;
            }
        }
    }
}