//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetDocomCertificateRequest
    {
        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" + "")]
        public TracesNT.WebServices.SecurityHeaderType Security;
        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/base/v4")]
        public string WebServiceClientId;
        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/base/v4")]
        public TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode;
        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/base/v4")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Attribute", IsNullable = false)]
        public TracesNT.WebServices.AttributeType[] Attributes;
        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetDocomCertificateRequest", Namespace = "http://ec.europa.eu/tracesnt/certificate/docom/retrieval/v1", Order = 0)]
        public TracesNT.WebServices.GetDocomCertificateRequestType GetDocomCertificateRequest1;
        public GetDocomCertificateRequest()
        {
        }

        public GetDocomCertificateRequest(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.GetDocomCertificateRequestType GetDocomCertificateRequest1)
        {
            this.Security = Security;
            this.WebServiceClientId = WebServiceClientId;
            this.LanguageCode = LanguageCode;
            this.Attributes = Attributes;
            this.GetDocomCertificateRequest1 = GetDocomCertificateRequest1;
        }
    }
}