//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetEuIntraSignedPdfCertificateResponse
    {
        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetEuIntraSignedPdfCertificateResponse", Namespace = "http://ec.europa.eu/tracesnt/certificate/euintra/v1", Order = 0)]
        public TracesNT.WebServices.PdfCertificateType GetEuIntraSignedPdfCertificateResponse1;
        public GetEuIntraSignedPdfCertificateResponse()
        {
        }

        public GetEuIntraSignedPdfCertificateResponse(TracesNT.WebServices.PdfCertificateType GetEuIntraSignedPdfCertificateResponse1)
        {
            this.GetEuIntraSignedPdfCertificateResponse1 = GetEuIntraSignedPdfCertificateResponse1;
        }
    }
}