//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class GetLaboratoryTestCategoriesResponse
    {
        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/message/v1")]
        public TracesNT.WebServices.MessageType Message;
        [System.ServiceModel.MessageBodyMemberAttribute(Name = "GetLaboratoryTestCategoriesResponse", Namespace = "http://ec.europa.eu/tracesnt/referencedata/v1", Order = 0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LaboratoryTestCategory", IsNullable = false)]
        public TracesNT.WebServices.LaboratoryTestCategoryType[] GetLaboratoryTestCategoriesResponse1;
        public GetLaboratoryTestCategoriesResponse()
        {
        }

        public GetLaboratoryTestCategoriesResponse(TracesNT.WebServices.MessageType Message, TracesNT.WebServices.LaboratoryTestCategoryType[] GetLaboratoryTestCategoriesResponse1)
        {
            this.Message = Message;
            this.GetLaboratoryTestCategoriesResponse1 = GetLaboratoryTestCategoriesResponse1;
        }
    }
}