//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ChedClearanceRequest
    {
        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" + "")]
        public TracesNT.WebServices.CertexServices.SecurityHeaderType Security;
        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/base/v3")]
        public string WebServiceClientId;
        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/base/v3")]
        public TracesNT.WebServices.CertexServices.ISO2AlphaLanguageCodeContentType LanguageCode;
        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://ec.europa.eu/tracesnt/body/v1")]
        public string CustomsOfficeReferenceNumber;
        [System.ServiceModel.MessageHeaderAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/ched/v06")]
        public TracesNT.WebServices.CertexHeaderType CertexHeader;
        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ChedClearanceRequest", Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/ched/v06", Order = 0)]
        public TracesNT.WebServices.ChedClearanceRequestType ChedClearanceRequest1;
        public ChedClearanceRequest()
        {
        }

        public ChedClearanceRequest(TracesNT.WebServices.CertexServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.CertexServices.ISO2AlphaLanguageCodeContentType LanguageCode, string CustomsOfficeReferenceNumber, TracesNT.WebServices.CertexServices.CertexHeaderType CertexHeader, TracesNT.WebServices.CertexServices.ChedClearanceRequestType ChedClearanceRequest1)
        {
            this.Security = Security;
            this.WebServiceClientId = WebServiceClientId;
            this.LanguageCode = LanguageCode;
            this.CustomsOfficeReferenceNumber = CustomsOfficeReferenceNumber;
            this.CertexHeader = CertexHeader;
            this.ChedClearanceRequest1 = ChedClearanceRequest1;
        }
    }
}