//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/ched/v04")]
    public partial class ChedInterventionRequestType
    {
        private CompetentCustomsOfficeType competentCustomsOfficeField;
        private System.DateTime sendingDateField;
        private string customsDocumentReferenceField;
        private string tARICDocumentField;
        private string chedCertificateIdField;
        private ConsignmentItemEnhancedR4ForInterventionType[] consignmentItemField;
        private InterventionMessageInformationType interventionTypeField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CompetentCustomsOfficeType CompetentCustomsOffice
        {
            get
            {
                return this.competentCustomsOfficeField;
            }

            set
            {
                this.competentCustomsOfficeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.DateTime SendingDate
        {
            get
            {
                return this.sendingDateField;
            }

            set
            {
                this.sendingDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string CustomsDocumentReference
        {
            get
            {
                return this.customsDocumentReferenceField;
            }

            set
            {
                this.customsDocumentReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public string TARICDocument
        {
            get
            {
                return this.tARICDocumentField;
            }

            set
            {
                this.tARICDocumentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token", Order = 4)]
        public string ChedCertificateId
        {
            get
            {
                return this.chedCertificateIdField;
            }

            set
            {
                this.chedCertificateIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConsignmentItem", Order = 5)]
        public ConsignmentItemEnhancedR4ForInterventionType[] ConsignmentItem
        {
            get
            {
                return this.consignmentItemField;
            }

            set
            {
                this.consignmentItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public InterventionMessageInformationType InterventionType
        {
            get
            {
                return this.interventionTypeField;
            }

            set
            {
                this.interventionTypeField = value;
            }
        }
    }
}