//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/ched/v06")]
    public partial class ProcessedChedInformationResponseType
    {
        private CertificateChedType chedCertificateField;
        private QuantityManagementCommoditySummaryEnhanced4ChedR51Type quantityManagementSummaryField;
        private string operationCodeField;
        private PdfCertificateType chedPdfCertificateField;
        private bool reservationResultField;
        private bool reservationResultFieldSpecified;
        private string reservationFailureReasonField;
        private ReservationFailureConsignmentItemType reservationFailureConsignmentItemField;
        private QuantitiesPrevalidationResultEnhancedType prevalidationResultField;
        private bool pushActiveField;
        private PushStopReasonType pushStopReasonField;
        private bool pushStopReasonFieldSpecified;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CertificateChedType ChedCertificate
        {
            get
            {
                return this.chedCertificateField;
            }

            set
            {
                this.chedCertificateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public QuantityManagementCommoditySummaryEnhanced4ChedR51Type QuantityManagementSummary
        {
            get
            {
                return this.quantityManagementSummaryField;
            }

            set
            {
                this.quantityManagementSummaryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 2)]
        public string OperationCode
        {
            get
            {
                return this.operationCodeField;
            }

            set
            {
                this.operationCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public PdfCertificateType ChedPdfCertificate
        {
            get
            {
                return this.chedPdfCertificateField;
            }

            set
            {
                this.chedPdfCertificateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public bool ReservationResult
        {
            get
            {
                return this.reservationResultField;
            }

            set
            {
                this.reservationResultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReservationResultSpecified
        {
            get
            {
                return this.reservationResultFieldSpecified;
            }

            set
            {
                this.reservationResultFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public string ReservationFailureReason
        {
            get
            {
                return this.reservationFailureReasonField;
            }

            set
            {
                this.reservationFailureReasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public ReservationFailureConsignmentItemType ReservationFailureConsignmentItem
        {
            get
            {
                return this.reservationFailureConsignmentItemField;
            }

            set
            {
                this.reservationFailureConsignmentItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public QuantitiesPrevalidationResultEnhancedType PrevalidationResult
        {
            get
            {
                return this.prevalidationResultField;
            }

            set
            {
                this.prevalidationResultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public bool PushActive
        {
            get
            {
                return this.pushActiveField;
            }

            set
            {
                this.pushActiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public PushStopReasonType PushStopReason
        {
            get
            {
                return this.pushStopReasonField;
            }

            set
            {
                this.pushStopReasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PushStopReasonSpecified
        {
            get
            {
                return this.pushStopReasonFieldSpecified;
            }

            set
            {
                this.pushStopReasonFieldSpecified = value;
            }
        }
    }
}