//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CertificateAttachmentsPortClient : System.ServiceModel.ClientBase<TracesNT.WebServices.CertificateAttachmentsPort>, TracesNT.WebServices.CertificateAttachmentsPort
    {
        public CertificateAttachmentsPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetCertificateAttachmentResponse> TracesNT.WebServices.CertificateAttachmentsPort.getCertificateAttachmentAsync(TracesNT.WebServices.GetCertificateAttachmentRequest request)
        {
            return base.Channel.getCertificateAttachmentAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.GetCertificateAttachmentResponse> getCertificateAttachmentAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.GetCertificateAttachmentRequestType GetCertificateAttachmentRequest1)
        {
            TracesNT.WebServices.GetCertificateAttachmentRequest inValue = new TracesNT.WebServices.GetCertificateAttachmentRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.GetCertificateAttachmentRequest1 = GetCertificateAttachmentRequest1;
            return ((TracesNT.WebServices.CertificateAttachmentsPort)(this)).getCertificateAttachmentAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.SubmitCertificateAttachmentResponse> TracesNT.WebServices.CertificateAttachmentsPort.submitCertificateAttachmentAsync(TracesNT.WebServices.SubmitCertificateAttachmentRequest request)
        {
            return base.Channel.submitCertificateAttachmentAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.SubmitCertificateAttachmentResponse> submitCertificateAttachmentAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.CertificateAttachmentType SubmitCertificateAttachmentRequest1)
        {
            TracesNT.WebServices.SubmitCertificateAttachmentRequest inValue = new TracesNT.WebServices.SubmitCertificateAttachmentRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.SubmitCertificateAttachmentRequest1 = SubmitCertificateAttachmentRequest1;
            return ((TracesNT.WebServices.CertificateAttachmentsPort)(this)).submitCertificateAttachmentAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

#if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
#endif
    }
}