//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ChedCertificatePortClient : System.ServiceModel.ClientBase<TracesNT.WebServices.ChedCertificatePort>, TracesNT.WebServices.ChedCertificatePort
    {
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name = "serviceEndpoint">The endpoint to configure</param>
        /// <param name = "clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        public ChedCertificatePortClient() : base(ChedCertificatePortClient.GetDefaultBinding(), ChedCertificatePortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ChedCertificateServiceV2Endpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ChedCertificatePortClient(EndpointConfiguration endpointConfiguration) : base(ChedCertificatePortClient.GetBindingForEndpoint(endpointConfiguration), ChedCertificatePortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ChedCertificatePortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : base(ChedCertificatePortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ChedCertificatePortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : base(ChedCertificatePortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public ChedCertificatePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetChedCertificateResponse> TracesNT.WebServices.ChedCertificatePort.getChedCertificateAsync(TracesNT.WebServices.GetChedCertificateRequest request)
        {
            return base.Channel.getChedCertificateAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.GetChedCertificateResponse> getChedCertificateAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.GetChedCertificateRequestType GetChedCertificateRequest1)
        {
            TracesNT.WebServices.GetChedCertificateRequest inValue = new TracesNT.WebServices.GetChedCertificateRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.GetChedCertificateRequest1 = GetChedCertificateRequest1;
            return ((TracesNT.WebServices.ChedCertificatePort)(this)).getChedCertificateAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetChedFollowUpResponse> TracesNT.WebServices.ChedCertificatePort.getChedFollowUpAsync(TracesNT.WebServices.GetChedFollowUpRequest request)
        {
            return base.Channel.getChedFollowUpAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.GetChedFollowUpResponse> getChedFollowUpAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.GetChedFollowUpRequestType GetChedFollowUpRequest1)
        {
            TracesNT.WebServices.GetChedFollowUpRequest inValue = new TracesNT.WebServices.GetChedFollowUpRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.GetChedFollowUpRequest1 = GetChedFollowUpRequest1;
            return ((TracesNT.WebServices.ChedCertificatePort)(this)).getChedFollowUpAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetChedNonComplianceDetailsResponse> TracesNT.WebServices.ChedCertificatePort.getChedNonComplianceDetailsAsync(TracesNT.WebServices.GetChedNonComplianceDetailsRequest request)
        {
            return base.Channel.getChedNonComplianceDetailsAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.GetChedNonComplianceDetailsResponse> getChedNonComplianceDetailsAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.GetChedNonComplianceDetailsRequestType GetChedNonComplianceDetailsRequest1)
        {
            TracesNT.WebServices.GetChedNonComplianceDetailsRequest inValue = new TracesNT.WebServices.GetChedNonComplianceDetailsRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.GetChedNonComplianceDetailsRequest1 = GetChedNonComplianceDetailsRequest1;
            return ((TracesNT.WebServices.ChedCertificatePort)(this)).getChedNonComplianceDetailsAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetChedLaboratoryTestsResponse> TracesNT.WebServices.ChedCertificatePort.getChedLaboratoryTestsAsync(TracesNT.WebServices.GetChedLaboratoryTestsRequest request)
        {
            return base.Channel.getChedLaboratoryTestsAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.GetChedLaboratoryTestsResponse> getChedLaboratoryTestsAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.GetChedLaboratoryTestsRequestType GetChedLaboratoryTestsRequest1)
        {
            TracesNT.WebServices.GetChedLaboratoryTestsRequest inValue = new TracesNT.WebServices.GetChedLaboratoryTestsRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.GetChedLaboratoryTestsRequest1 = GetChedLaboratoryTestsRequest1;
            return ((TracesNT.WebServices.ChedCertificatePort)(this)).getChedLaboratoryTestsAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetChedPdfCertificateResponse> TracesNT.WebServices.ChedCertificatePort.getChedPdfCertificateAsync(TracesNT.WebServices.GetChedPdfCertificateRequest request)
        {
            return base.Channel.getChedPdfCertificateAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.GetChedPdfCertificateResponse> getChedPdfCertificateAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.GetChedPdfCertificateRequestType GetChedPdfCertificateRequest1)
        {
            TracesNT.WebServices.GetChedPdfCertificateRequest inValue = new TracesNT.WebServices.GetChedPdfCertificateRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.GetChedPdfCertificateRequest1 = GetChedPdfCertificateRequest1;
            return ((TracesNT.WebServices.ChedCertificatePort)(this)).getChedPdfCertificateAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetChedSignedPdfCertificateResponse> TracesNT.WebServices.ChedCertificatePort.getChedSignedPdfCertificateAsync(TracesNT.WebServices.GetChedSignedPdfCertificateRequest request)
        {
            return base.Channel.getChedSignedPdfCertificateAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.GetChedSignedPdfCertificateResponse> getChedSignedPdfCertificateAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.GetChedSignedPdfCertificateRequestType GetChedSignedPdfCertificateRequest1)
        {
            TracesNT.WebServices.GetChedSignedPdfCertificateRequest inValue = new TracesNT.WebServices.GetChedSignedPdfCertificateRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.GetChedSignedPdfCertificateRequest1 = GetChedSignedPdfCertificateRequest1;
            return ((TracesNT.WebServices.ChedCertificatePort)(this)).getChedSignedPdfCertificateAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetChedSignedXmlCertificateResponse> TracesNT.WebServices.ChedCertificatePort.getChedSignedXmlCertificateAsync(TracesNT.WebServices.GetChedSignedXmlCertificateRequest request)
        {
            return base.Channel.getChedSignedXmlCertificateAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.GetChedSignedXmlCertificateResponse> getChedSignedXmlCertificateAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.GetChedSignedXmlCertificateRequestType GetChedSignedXmlCertificateRequest1)
        {
            TracesNT.WebServices.GetChedSignedXmlCertificateRequest inValue = new TracesNT.WebServices.GetChedSignedXmlCertificateRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.GetChedSignedXmlCertificateRequest1 = GetChedSignedXmlCertificateRequest1;
            return ((TracesNT.WebServices.ChedCertificatePort)(this)).getChedSignedXmlCertificateAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.FindChedCertificateResponse> TracesNT.WebServices.ChedCertificatePort.findChedCertificateAsync(TracesNT.WebServices.FindChedCertificateRequest request)
        {
            return base.Channel.findChedCertificateAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.FindChedCertificateResponse> findChedCertificateAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.FindChedCertificateRequestType FindChedCertificateRequest1)
        {
            TracesNT.WebServices.FindChedCertificateRequest inValue = new TracesNT.WebServices.FindChedCertificateRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.FindChedCertificateRequest1 = FindChedCertificateRequest1;
            return ((TracesNT.WebServices.ChedCertificatePort)(this)).findChedCertificateAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetChedCertificateStatusResponse> TracesNT.WebServices.ChedCertificatePort.getChedCertificateStatusAsync(TracesNT.WebServices.GetChedCertificateStatusRequest request)
        {
            return base.Channel.getChedCertificateStatusAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.GetChedCertificateStatusResponse> getChedCertificateStatusAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, string[] GetChedCertificateStatusRequest1)
        {
            TracesNT.WebServices.GetChedCertificateStatusRequest inValue = new TracesNT.WebServices.GetChedCertificateStatusRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.GetChedCertificateStatusRequest1 = GetChedCertificateStatusRequest1;
            return ((TracesNT.WebServices.ChedCertificatePort)(this)).getChedCertificateStatusAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

#if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

#endif
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ChedCertificateServiceV2Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ChedCertificateServiceV2Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://webgate.acceptance.ec.europa.eu/tracesnt/ws/ChedCertificateServiceV2");
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ChedCertificatePortClient.GetBindingForEndpoint(EndpointConfiguration.ChedCertificateServiceV2Endpoint);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ChedCertificatePortClient.GetEndpointAddress(EndpointConfiguration.ChedCertificateServiceV2Endpoint);
        }

        public enum EndpointConfiguration
        {
            ChedCertificateServiceV2Endpoint,
        }
    }
}