//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CustomsCertexChedPortClient : System.ServiceModel.ClientBase<TracesNT.WebServices.CustomsCertexChedPort>, TracesNT.WebServices.CustomsCertexChedPort
    {
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name = "serviceEndpoint">The endpoint to configure</param>
        /// <param name = "clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        public CustomsCertexChedPortClient() : base(CustomsCertexChedPortClient.GetDefaultBinding(), CustomsCertexChedPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CustomsCertexChedServiceV06Endpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public CustomsCertexChedPortClient(EndpointConfiguration endpointConfiguration) : base(CustomsCertexChedPortClient.GetBindingForEndpoint(endpointConfiguration), CustomsCertexChedPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public CustomsCertexChedPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : base(CustomsCertexChedPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public CustomsCertexChedPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : base(CustomsCertexChedPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public CustomsCertexChedPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.ProcessedChedInformationResponse> TracesNT.WebServices.CustomsCertexChedPort.processedChedRequestAsync(TracesNT.WebServices.ProcessedChedRequest request)
        {
            return base.Channel.processedChedRequestAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.ProcessedChedInformationResponse> processedChedRequestAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, string CustomsOfficeReferenceNumber, TracesNT.WebServices.CertexHeaderType CertexHeader, TracesNT.WebServices.ProcessedChedRequestType ProcessedChedRequest1)
        {
            TracesNT.WebServices.ProcessedChedRequest inValue = new TracesNT.WebServices.ProcessedChedRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.CustomsOfficeReferenceNumber = CustomsOfficeReferenceNumber;
            inValue.CertexHeader = CertexHeader;
            inValue.ProcessedChedRequest1 = ProcessedChedRequest1;
            return ((TracesNT.WebServices.CustomsCertexChedPort)(this)).processedChedRequestAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.ChedClearanceResponse> TracesNT.WebServices.CustomsCertexChedPort.chedClearanceRequestAsync(TracesNT.WebServices.ChedClearanceRequest request)
        {
            return base.Channel.chedClearanceRequestAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.ChedClearanceResponse> chedClearanceRequestAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, string CustomsOfficeReferenceNumber, TracesNT.WebServices.CertexHeaderType CertexHeader, TracesNT.WebServices.ChedClearanceRequestType ChedClearanceRequest1)
        {
            TracesNT.WebServices.ChedClearanceRequest inValue = new TracesNT.WebServices.ChedClearanceRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.CustomsOfficeReferenceNumber = CustomsOfficeReferenceNumber;
            inValue.CertexHeader = CertexHeader;
            inValue.ChedClearanceRequest1 = ChedClearanceRequest1;
            return ((TracesNT.WebServices.CustomsCertexChedPort)(this)).chedClearanceRequestAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.ChedInterventionResponse> TracesNT.WebServices.CustomsCertexChedPort.chedInterventionRequestAsync(TracesNT.WebServices.ChedInterventionRequest request)
        {
            return base.Channel.chedInterventionRequestAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.ChedInterventionResponse> chedInterventionRequestAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, string CustomsOfficeReferenceNumber, TracesNT.WebServices.CertexHeaderType CertexHeader, TracesNT.WebServices.ChedInterventionRequestType ChedInterventionRequest1)
        {
            TracesNT.WebServices.ChedInterventionRequest inValue = new TracesNT.WebServices.ChedInterventionRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.CustomsOfficeReferenceNumber = CustomsOfficeReferenceNumber;
            inValue.CertexHeader = CertexHeader;
            inValue.ChedInterventionRequest1 = ChedInterventionRequest1;
            return ((TracesNT.WebServices.CustomsCertexChedPort)(this)).chedInterventionRequestAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.ChedCRFLResponse> TracesNT.WebServices.CustomsCertexChedPort.chedCRFLRequestAsync(TracesNT.WebServices.ChedCRFLRequest request)
        {
            return base.Channel.chedCRFLRequestAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.ChedCRFLResponse> chedCRFLRequestAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, string CustomsOfficeReferenceNumber, TracesNT.WebServices.CertexHeaderType CertexHeader, TracesNT.WebServices.ChedCRFLRequestType ChedCRFLRequest1)
        {
            TracesNT.WebServices.ChedCRFLRequest inValue = new TracesNT.WebServices.ChedCRFLRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.CustomsOfficeReferenceNumber = CustomsOfficeReferenceNumber;
            inValue.CertexHeader = CertexHeader;
            inValue.ChedCRFLRequest1 = ChedCRFLRequest1;
            return ((TracesNT.WebServices.CustomsCertexChedPort)(this)).chedCRFLRequestAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

#if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

#endif
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomsCertexChedServiceV06Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomsCertexChedServiceV06Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://webgate.acceptance.ec.europa.eu/tracesnt/ws/CustomsCertexChedServiceV06");
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CustomsCertexChedPortClient.GetBindingForEndpoint(EndpointConfiguration.CustomsCertexChedServiceV06Endpoint);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CustomsCertexChedPortClient.GetEndpointAddress(EndpointConfiguration.CustomsCertexChedServiceV06Endpoint);
        }

        public enum EndpointConfiguration
        {
            CustomsCertexChedServiceV06Endpoint,
        }
    }
}