//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class DocomCertificateRetrievalPortClient : System.ServiceModel.ClientBase<TracesNT.WebServices.DocomCertificateRetrievalPort>, TracesNT.WebServices.DocomCertificateRetrievalPort
    {
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name = "serviceEndpoint">The endpoint to configure</param>
        /// <param name = "clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        public DocomCertificateRetrievalPortClient() : base(DocomCertificateRetrievalPortClient.GetDefaultBinding(), DocomCertificateRetrievalPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.DocomCertificateRetrievalServiceV1Endpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DocomCertificateRetrievalPortClient(EndpointConfiguration endpointConfiguration) : base(DocomCertificateRetrievalPortClient.GetBindingForEndpoint(endpointConfiguration), DocomCertificateRetrievalPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DocomCertificateRetrievalPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : base(DocomCertificateRetrievalPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DocomCertificateRetrievalPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : base(DocomCertificateRetrievalPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DocomCertificateRetrievalPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetDocomCertificateResponse> TracesNT.WebServices.DocomCertificateRetrievalPort.getDocomCertificateAsync(TracesNT.WebServices.GetDocomCertificateRequest request)
        {
            return base.Channel.getDocomCertificateAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.GetDocomCertificateResponse> getDocomCertificateAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.GetDocomCertificateRequestType GetDocomCertificateRequest1)
        {
            TracesNT.WebServices.GetDocomCertificateRequest inValue = new TracesNT.WebServices.GetDocomCertificateRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.GetDocomCertificateRequest1 = GetDocomCertificateRequest1;
            return ((TracesNT.WebServices.DocomCertificateRetrievalPort)(this)).getDocomCertificateAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetDocomPdfCertificateResponse> TracesNT.WebServices.DocomCertificateRetrievalPort.getDocomPdfCertificateAsync(TracesNT.WebServices.GetDocomPdfCertificateRequest request)
        {
            return base.Channel.getDocomPdfCertificateAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.GetDocomPdfCertificateResponse> getDocomPdfCertificateAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.GetDocomPdfCertificateRequestType GetDocomPdfCertificateRequest1)
        {
            TracesNT.WebServices.GetDocomPdfCertificateRequest inValue = new TracesNT.WebServices.GetDocomPdfCertificateRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.GetDocomPdfCertificateRequest1 = GetDocomPdfCertificateRequest1;
            return ((TracesNT.WebServices.DocomCertificateRetrievalPort)(this)).getDocomPdfCertificateAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.FindDocomCertificateResponse> TracesNT.WebServices.DocomCertificateRetrievalPort.findDocomCertificateAsync(TracesNT.WebServices.FindDocomCertificateRequest request)
        {
            return base.Channel.findDocomCertificateAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.FindDocomCertificateResponse> findDocomCertificateAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.FindDocomCertificateRequestType FindDocomCertificateRequest1)
        {
            TracesNT.WebServices.FindDocomCertificateRequest inValue = new TracesNT.WebServices.FindDocomCertificateRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.FindDocomCertificateRequest1 = FindDocomCertificateRequest1;
            return ((TracesNT.WebServices.DocomCertificateRetrievalPort)(this)).findDocomCertificateAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

#if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

#endif
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocomCertificateRetrievalServiceV1Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DocomCertificateRetrievalServiceV1Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://webgate.acceptance.ec.europa.eu/tracesnt/ws/DocomCertificateRetrievalServ" + "iceV1");
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return DocomCertificateRetrievalPortClient.GetBindingForEndpoint(EndpointConfiguration.DocomCertificateRetrievalServiceV1Endpoint);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return DocomCertificateRetrievalPortClient.GetEndpointAddress(EndpointConfiguration.DocomCertificateRetrievalServiceV1Endpoint);
        }

        public enum EndpointConfiguration
        {
            DocomCertificateRetrievalServiceV1Endpoint,
        }
    }
}