//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class EuIntraCertificatePortClient : System.ServiceModel.ClientBase<TracesNT.WebServices.EuIntraCertificatePort>, TracesNT.WebServices.EuIntraCertificatePort
    {
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name = "serviceEndpoint">The endpoint to configure</param>
        /// <param name = "clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        public EuIntraCertificatePortClient() : base(EuIntraCertificatePortClient.GetDefaultBinding(), EuIntraCertificatePortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.EuIntraCertificateServiceV1Endpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public EuIntraCertificatePortClient(EndpointConfiguration endpointConfiguration) : base(EuIntraCertificatePortClient.GetBindingForEndpoint(endpointConfiguration), EuIntraCertificatePortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public EuIntraCertificatePortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : base(EuIntraCertificatePortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public EuIntraCertificatePortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : base(EuIntraCertificatePortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public EuIntraCertificatePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetEuIntraCertificateResponse> TracesNT.WebServices.EuIntraCertificatePort.getEuIntraCertificateAsync(TracesNT.WebServices.GetEuIntraCertificateRequest request)
        {
            return base.Channel.getEuIntraCertificateAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.GetEuIntraCertificateResponse> getEuIntraCertificateAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.GetEuIntraCertificateRequestType GetEuIntraCertificateRequest1)
        {
            TracesNT.WebServices.GetEuIntraCertificateRequest inValue = new TracesNT.WebServices.GetEuIntraCertificateRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.GetEuIntraCertificateRequest1 = GetEuIntraCertificateRequest1;
            return ((TracesNT.WebServices.EuIntraCertificatePort)(this)).getEuIntraCertificateAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetEuIntraPdfCertificateResponse> TracesNT.WebServices.EuIntraCertificatePort.getEuIntraPdfCertificateAsync(TracesNT.WebServices.GetEuIntraPdfCertificateRequest request)
        {
            return base.Channel.getEuIntraPdfCertificateAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.GetEuIntraPdfCertificateResponse> getEuIntraPdfCertificateAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.GetEuIntraPdfCertificateRequestType GetEuIntraPdfCertificateRequest1)
        {
            TracesNT.WebServices.GetEuIntraPdfCertificateRequest inValue = new TracesNT.WebServices.GetEuIntraPdfCertificateRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.GetEuIntraPdfCertificateRequest1 = GetEuIntraPdfCertificateRequest1;
            return ((TracesNT.WebServices.EuIntraCertificatePort)(this)).getEuIntraPdfCertificateAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetEuIntraSignedPdfCertificateResponse> TracesNT.WebServices.EuIntraCertificatePort.getEuIntraSignedPdfCertificateAsync(TracesNT.WebServices.GetEuIntraSignedPdfCertificateRequest request)
        {
            return base.Channel.getEuIntraSignedPdfCertificateAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.GetEuIntraSignedPdfCertificateResponse> getEuIntraSignedPdfCertificateAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.GetEuIntraSignedPdfCertificateRequestType GetEuIntraSignedPdfCertificateRequest1)
        {
            TracesNT.WebServices.GetEuIntraSignedPdfCertificateRequest inValue = new TracesNT.WebServices.GetEuIntraSignedPdfCertificateRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.GetEuIntraSignedPdfCertificateRequest1 = GetEuIntraSignedPdfCertificateRequest1;
            return ((TracesNT.WebServices.EuIntraCertificatePort)(this)).getEuIntraSignedPdfCertificateAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.FindEuIntraCertificateResponse> TracesNT.WebServices.EuIntraCertificatePort.findEuIntraCertificateAsync(TracesNT.WebServices.FindEuIntraCertificateRequest request)
        {
            return base.Channel.findEuIntraCertificateAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.FindEuIntraCertificateResponse> findEuIntraCertificateAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, TracesNT.WebServices.FindEuIntraCertificateRequestType FindEuIntraCertificateRequest1)
        {
            TracesNT.WebServices.FindEuIntraCertificateRequest inValue = new TracesNT.WebServices.FindEuIntraCertificateRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.FindEuIntraCertificateRequest1 = FindEuIntraCertificateRequest1;
            return ((TracesNT.WebServices.EuIntraCertificatePort)(this)).findEuIntraCertificateAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetEuIntraCertificateStatusResponse> TracesNT.WebServices.EuIntraCertificatePort.getEuIntraCertificateStatusAsync(TracesNT.WebServices.GetEuIntraCertificateStatusRequest request)
        {
            return base.Channel.getEuIntraCertificateStatusAsync(request);
        }

        public System.Threading.Tasks.Task<TracesNT.WebServices.GetEuIntraCertificateStatusResponse> getEuIntraCertificateStatusAsync(TracesNT.WebServices.SecurityHeaderType Security, string WebServiceClientId, TracesNT.WebServices.ISO2AlphaLanguageCodeContentType LanguageCode, TracesNT.WebServices.AttributeType[] Attributes, string[] GetEuIntraCertificateStatusRequest1)
        {
            TracesNT.WebServices.GetEuIntraCertificateStatusRequest inValue = new TracesNT.WebServices.GetEuIntraCertificateStatusRequest();
            inValue.Security = Security;
            inValue.WebServiceClientId = WebServiceClientId;
            inValue.LanguageCode = LanguageCode;
            inValue.Attributes = Attributes;
            inValue.GetEuIntraCertificateStatusRequest1 = GetEuIntraCertificateStatusRequest1;
            return ((TracesNT.WebServices.EuIntraCertificatePort)(this)).getEuIntraCertificateStatusAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

#if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

#endif
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EuIntraCertificateServiceV1Endpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.EuIntraCertificateServiceV1Endpoint))
            {
                return new System.ServiceModel.EndpointAddress("https://webgate.acceptance.ec.europa.eu/tracesnt/ws/EuIntraCertificateServiceV1");
            }

            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return EuIntraCertificatePortClient.GetBindingForEndpoint(EndpointConfiguration.EuIntraCertificateServiceV1Endpoint);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return EuIntraCertificatePortClient.GetEndpointAddress(EndpointConfiguration.EuIntraCertificateServiceV1Endpoint);
        }

        public enum EndpointConfiguration
        {
            EuIntraCertificateServiceV1Endpoint,
        }
    }
}