//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/base/v03")]
    public partial class AllocatedProductQuantityByCustomsOfficeEnhanced4ChedR4Type
    {
        private string goodsItemNumberField;
        private CommodityCodeType commodityCodeField;
        private QuantityR4ForInterventionAllocationType quantityField;
        private System.DateTime sendingDateField;
        private bool sendingDateFieldSpecified;
        private CompetentCustomsOfficeType competentCustomsOfficeField;
        private string itemField;
        private ItemChoiceType itemElementNameField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
        public string GoodsItemNumber
        {
            get
            {
                return this.goodsItemNumberField;
            }

            set
            {
                this.goodsItemNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public CommodityCodeType CommodityCode
        {
            get
            {
                return this.commodityCodeField;
            }

            set
            {
                this.commodityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public QuantityR4ForInterventionAllocationType Quantity
        {
            get
            {
                return this.quantityField;
            }

            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public System.DateTime SendingDate
        {
            get
            {
                return this.sendingDateField;
            }

            set
            {
                this.sendingDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SendingDateSpecified
        {
            get
            {
                return this.sendingDateFieldSpecified;
            }

            set
            {
                this.sendingDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public CompetentCustomsOfficeType CompetentCustomsOffice
        {
            get
            {
                return this.competentCustomsOfficeField;
            }

            set
            {
                this.competentCustomsOfficeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("LRN", typeof(string), Order = 5)]
        [System.Xml.Serialization.XmlElementAttribute("MRN", typeof(string), Order = 5)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }

            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }

            set
            {
                this.itemElementNameField = value;
            }
        }
    }
}