//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/ched/v06")]
    public partial class CertificateChedType
    {
        private SPSCertificateType sPSCertificateField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:un:unece:uncefact:data:standard:SPSCertificate:17", Order = 0)]
        public SPSCertificateType SPSCertificate
        {
            get
            {
                return this.sPSCertificateField;
            }

            set
            {
                this.sPSCertificateField = value;
            }
        }
    }
}