//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/base/v03")]
    public partial class CRFLCHEDFilters4ConsignmentType
    {
        private string[] countryOfOriginField;
        private string[] commodityCodeField;
        private bool cNCodeExactMatchField;
        private bool cNCodeExactMatchFieldSpecified;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CountryOfOrigin", Order = 0)]
        public string[] CountryOfOrigin
        {
            get
            {
                return this.countryOfOriginField;
            }

            set
            {
                this.countryOfOriginField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommodityCode", Order = 1)]
        public string[] CommodityCode
        {
            get
            {
                return this.commodityCodeField;
            }

            set
            {
                this.commodityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public bool CNCodeExactMatch
        {
            get
            {
                return this.cNCodeExactMatchField;
            }

            set
            {
                this.cNCodeExactMatchField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CNCodeExactMatchSpecified
        {
            get
            {
                return this.cNCodeExactMatchFieldSpecified;
            }

            set
            {
                this.cNCodeExactMatchFieldSpecified = value;
            }
        }
    }
}