//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:un:unece:uncefact:codelist:standard:UNECE:DocumentNameCode:D16B")]
    public enum DocumentNameCodeContentType
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("19")]
        Item19,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("22")]
        Item22,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("23")]
        Item23,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("24")]
        Item24,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25")]
        Item25,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("26")]
        Item26,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27")]
        Item27,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("28")]
        Item28,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("29")]
        Item29,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("31")]
        Item31,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32")]
        Item32,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("33")]
        Item33,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("34")]
        Item34,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("35")]
        Item35,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("36")]
        Item36,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("37")]
        Item37,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("38")]
        Item38,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("39")]
        Item39,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("41")]
        Item41,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43")]
        Item43,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44")]
        Item44,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("45")]
        Item45,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("46")]
        Item46,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("47")]
        Item47,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("48")]
        Item48,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("49")]
        Item49,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("50")]
        Item50,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("51")]
        Item51,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("52")]
        Item52,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("53")]
        Item53,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("54")]
        Item54,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("55")]
        Item55,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("56")]
        Item56,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("57")]
        Item57,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("58")]
        Item58,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("59")]
        Item59,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("60")]
        Item60,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("61")]
        Item61,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("62")]
        Item62,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("63")]
        Item63,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("64")]
        Item64,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("65")]
        Item65,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("66")]
        Item66,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("67")]
        Item67,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("68")]
        Item68,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("69")]
        Item69,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("70")]
        Item70,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("71")]
        Item71,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("72")]
        Item72,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("73")]
        Item73,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("74")]
        Item74,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("75")]
        Item75,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("76")]
        Item76,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("77")]
        Item77,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("78")]
        Item78,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("79")]
        Item79,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("80")]
        Item80,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("81")]
        Item81,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("82")]
        Item82,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("83")]
        Item83,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("84")]
        Item84,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("85")]
        Item85,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("86")]
        Item86,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("87")]
        Item87,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("88")]
        Item88,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("89")]
        Item89,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("90")]
        Item90,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("91")]
        Item91,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("92")]
        Item92,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("93")]
        Item93,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("94")]
        Item94,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("95")]
        Item95,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("96")]
        Item96,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("97")]
        Item97,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("98")]
        Item98,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("100")]
        Item100,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("101")]
        Item101,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("102")]
        Item102,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("103")]
        Item103,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("104")]
        Item104,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("105")]
        Item105,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("106")]
        Item106,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("107")]
        Item107,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("108")]
        Item108,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("109")]
        Item109,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("110")]
        Item110,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("111")]
        Item111,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("112")]
        Item112,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("113")]
        Item113,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("114")]
        Item114,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("115")]
        Item115,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("116")]
        Item116,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("117")]
        Item117,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("118")]
        Item118,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("119")]
        Item119,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("120")]
        Item120,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("121")]
        Item121,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("122")]
        Item122,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("123")]
        Item123,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("124")]
        Item124,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("125")]
        Item125,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("126")]
        Item126,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("127")]
        Item127,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("128")]
        Item128,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("129")]
        Item129,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("130")]
        Item130,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("131")]
        Item131,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("132")]
        Item132,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("133")]
        Item133,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("134")]
        Item134,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("135")]
        Item135,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("136")]
        Item136,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("137")]
        Item137,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("138")]
        Item138,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("139")]
        Item139,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("140")]
        Item140,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("141")]
        Item141,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("142")]
        Item142,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("143")]
        Item143,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("144")]
        Item144,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("145")]
        Item145,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("146")]
        Item146,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("147")]
        Item147,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("148")]
        Item148,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("149")]
        Item149,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("150")]
        Item150,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("151")]
        Item151,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("152")]
        Item152,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("153")]
        Item153,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("154")]
        Item154,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("155")]
        Item155,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("156")]
        Item156,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("157")]
        Item157,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("158")]
        Item158,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("159")]
        Item159,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("160")]
        Item160,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("161")]
        Item161,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("162")]
        Item162,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("163")]
        Item163,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("164")]
        Item164,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("165")]
        Item165,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("166")]
        Item166,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("167")]
        Item167,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("168")]
        Item168,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("169")]
        Item169,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("170")]
        Item170,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("171")]
        Item171,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("172")]
        Item172,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("173")]
        Item173,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("174")]
        Item174,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("175")]
        Item175,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("176")]
        Item176,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("177")]
        Item177,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("178")]
        Item178,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("179")]
        Item179,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("180")]
        Item180,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("181")]
        Item181,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("182")]
        Item182,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("183")]
        Item183,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("184")]
        Item184,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("185")]
        Item185,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("186")]
        Item186,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("187")]
        Item187,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("188")]
        Item188,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("189")]
        Item189,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("190")]
        Item190,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("191")]
        Item191,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("192")]
        Item192,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("193")]
        Item193,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("194")]
        Item194,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("195")]
        Item195,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("196")]
        Item196,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("197")]
        Item197,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("198")]
        Item198,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("199")]
        Item199,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("200")]
        Item200,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("201")]
        Item201,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("202")]
        Item202,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("203")]
        Item203,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("204")]
        Item204,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("205")]
        Item205,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("206")]
        Item206,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("207")]
        Item207,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("208")]
        Item208,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("209")]
        Item209,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("210")]
        Item210,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("211")]
        Item211,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("212")]
        Item212,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("213")]
        Item213,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("214")]
        Item214,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("215")]
        Item215,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("216")]
        Item216,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("217")]
        Item217,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("218")]
        Item218,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("219")]
        Item219,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("220")]
        Item220,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("221")]
        Item221,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("222")]
        Item222,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("223")]
        Item223,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("224")]
        Item224,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("225")]
        Item225,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("226")]
        Item226,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("227")]
        Item227,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("228")]
        Item228,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("229")]
        Item229,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("230")]
        Item230,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("231")]
        Item231,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("232")]
        Item232,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("233")]
        Item233,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("234")]
        Item234,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("235")]
        Item235,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("236")]
        Item236,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("237")]
        Item237,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("238")]
        Item238,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("239")]
        Item239,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("240")]
        Item240,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("241")]
        Item241,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("242")]
        Item242,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("243")]
        Item243,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("244")]
        Item244,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("245")]
        Item245,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("246")]
        Item246,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("247")]
        Item247,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("248")]
        Item248,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("249")]
        Item249,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("250")]
        Item250,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("251")]
        Item251,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("252")]
        Item252,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("253")]
        Item253,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("254")]
        Item254,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("255")]
        Item255,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("256")]
        Item256,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("257")]
        Item257,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("258")]
        Item258,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("259")]
        Item259,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("261")]
        Item261,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("262")]
        Item262,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("263")]
        Item263,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("264")]
        Item264,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("265")]
        Item265,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("266")]
        Item266,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("267")]
        Item267,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("268")]
        Item268,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("269")]
        Item269,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("270")]
        Item270,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("271")]
        Item271,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("272")]
        Item272,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("273")]
        Item273,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("274")]
        Item274,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("275")]
        Item275,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("276")]
        Item276,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("277")]
        Item277,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("278")]
        Item278,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("279")]
        Item279,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("280")]
        Item280,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("281")]
        Item281,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("282")]
        Item282,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("283")]
        Item283,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("284")]
        Item284,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("285")]
        Item285,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("286")]
        Item286,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("287")]
        Item287,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("288")]
        Item288,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("289")]
        Item289,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("290")]
        Item290,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("291")]
        Item291,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("292")]
        Item292,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("293")]
        Item293,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("294")]
        Item294,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("295")]
        Item295,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("296")]
        Item296,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("297")]
        Item297,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("298")]
        Item298,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("299")]
        Item299,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("300")]
        Item300,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("301")]
        Item301,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("302")]
        Item302,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("303")]
        Item303,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("304")]
        Item304,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("305")]
        Item305,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("306")]
        Item306,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("307")]
        Item307,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("308")]
        Item308,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("309")]
        Item309,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("310")]
        Item310,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("311")]
        Item311,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("312")]
        Item312,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("313")]
        Item313,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("314")]
        Item314,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("315")]
        Item315,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("316")]
        Item316,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("317")]
        Item317,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("318")]
        Item318,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("319")]
        Item319,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("320")]
        Item320,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("321")]
        Item321,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("322")]
        Item322,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("323")]
        Item323,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("324")]
        Item324,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("325")]
        Item325,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("326")]
        Item326,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("327")]
        Item327,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("328")]
        Item328,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("329")]
        Item329,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("330")]
        Item330,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("331")]
        Item331,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("332")]
        Item332,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("333")]
        Item333,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("334")]
        Item334,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("335")]
        Item335,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("336")]
        Item336,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("337")]
        Item337,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("338")]
        Item338,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("339")]
        Item339,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("340")]
        Item340,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("341")]
        Item341,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("342")]
        Item342,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("343")]
        Item343,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("344")]
        Item344,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("345")]
        Item345,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("346")]
        Item346,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("347")]
        Item347,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("348")]
        Item348,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("349")]
        Item349,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("350")]
        Item350,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("351")]
        Item351,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("352")]
        Item352,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("353")]
        Item353,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("354")]
        Item354,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("355")]
        Item355,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("356")]
        Item356,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("357")]
        Item357,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("358")]
        Item358,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("359")]
        Item359,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("360")]
        Item360,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("361")]
        Item361,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("362")]
        Item362,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("363")]
        Item363,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("364")]
        Item364,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("365")]
        Item365,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("366")]
        Item366,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("367")]
        Item367,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("368")]
        Item368,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("369")]
        Item369,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("370")]
        Item370,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("371")]
        Item371,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("372")]
        Item372,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("373")]
        Item373,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("374")]
        Item374,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("375")]
        Item375,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("376")]
        Item376,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("377")]
        Item377,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("378")]
        Item378,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("379")]
        Item379,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("380")]
        Item380,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("381")]
        Item381,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("382")]
        Item382,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("383")]
        Item383,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("384")]
        Item384,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("385")]
        Item385,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("386")]
        Item386,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("387")]
        Item387,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("388")]
        Item388,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("389")]
        Item389,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("390")]
        Item390,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("391")]
        Item391,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("392")]
        Item392,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("393")]
        Item393,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("394")]
        Item394,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("395")]
        Item395,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("396")]
        Item396,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("397")]
        Item397,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("398")]
        Item398,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("399")]
        Item399,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("400")]
        Item400,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("401")]
        Item401,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("402")]
        Item402,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("403")]
        Item403,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("404")]
        Item404,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("405")]
        Item405,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("406")]
        Item406,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("407")]
        Item407,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("408")]
        Item408,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("409")]
        Item409,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("410")]
        Item410,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("411")]
        Item411,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("412")]
        Item412,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("413")]
        Item413,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("414")]
        Item414,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("415")]
        Item415,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("416")]
        Item416,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("417")]
        Item417,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("418")]
        Item418,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("419")]
        Item419,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("420")]
        Item420,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("421")]
        Item421,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("422")]
        Item422,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("423")]
        Item423,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("424")]
        Item424,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("425")]
        Item425,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("426")]
        Item426,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("427")]
        Item427,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("428")]
        Item428,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("429")]
        Item429,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("430")]
        Item430,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("431")]
        Item431,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("432")]
        Item432,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("433")]
        Item433,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("434")]
        Item434,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("435")]
        Item435,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("436")]
        Item436,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("437")]
        Item437,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("438")]
        Item438,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("439")]
        Item439,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("440")]
        Item440,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("441")]
        Item441,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("442")]
        Item442,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("443")]
        Item443,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("444")]
        Item444,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("445")]
        Item445,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("446")]
        Item446,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("447")]
        Item447,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("448")]
        Item448,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("449")]
        Item449,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("450")]
        Item450,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("451")]
        Item451,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("452")]
        Item452,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("453")]
        Item453,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("454")]
        Item454,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("455")]
        Item455,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("456")]
        Item456,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("457")]
        Item457,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("458")]
        Item458,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("459")]
        Item459,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("460")]
        Item460,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("461")]
        Item461,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("462")]
        Item462,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("463")]
        Item463,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("464")]
        Item464,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("465")]
        Item465,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("466")]
        Item466,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("467")]
        Item467,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("468")]
        Item468,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("469")]
        Item469,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("470")]
        Item470,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("481")]
        Item481,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("482")]
        Item482,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("483")]
        Item483,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("484")]
        Item484,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("485")]
        Item485,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("486")]
        Item486,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("487")]
        Item487,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("488")]
        Item488,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("489")]
        Item489,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("490")]
        Item490,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("491")]
        Item491,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("493")]
        Item493,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("494")]
        Item494,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("495")]
        Item495,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("496")]
        Item496,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("497")]
        Item497,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("498")]
        Item498,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("499")]
        Item499,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("520")]
        Item520,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("521")]
        Item521,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("522")]
        Item522,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("523")]
        Item523,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("524")]
        Item524,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("525")]
        Item525,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("526")]
        Item526,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("527")]
        Item527,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("528")]
        Item528,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("529")]
        Item529,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("530")]
        Item530,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("531")]
        Item531,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("532")]
        Item532,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("533")]
        Item533,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("534")]
        Item534,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("535")]
        Item535,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("536")]
        Item536,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("537")]
        Item537,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("538")]
        Item538,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("539")]
        Item539,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("550")]
        Item550,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("551")]
        Item551,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("552")]
        Item552,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("553")]
        Item553,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("554")]
        Item554,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("575")]
        Item575,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("576")]
        Item576,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("577")]
        Item577,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("578")]
        Item578,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("579")]
        Item579,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("580")]
        Item580,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("581")]
        Item581,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("582")]
        Item582,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("583")]
        Item583,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("584")]
        Item584,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("585")]
        Item585,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("586")]
        Item586,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("587")]
        Item587,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("588")]
        Item588,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("589")]
        Item589,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("610")]
        Item610,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("621")]
        Item621,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("622")]
        Item622,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("623")]
        Item623,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("624")]
        Item624,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("625")]
        Item625,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("626")]
        Item626,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("627")]
        Item627,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("628")]
        Item628,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("629")]
        Item629,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("630")]
        Item630,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("631")]
        Item631,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("632")]
        Item632,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("633")]
        Item633,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("634")]
        Item634,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("635")]
        Item635,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("636")]
        Item636,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("637")]
        Item637,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("638")]
        Item638,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("639")]
        Item639,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("640")]
        Item640,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("641")]
        Item641,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("642")]
        Item642,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("643")]
        Item643,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("644")]
        Item644,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("645")]
        Item645,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("646")]
        Item646,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("647")]
        Item647,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("648")]
        Item648,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("649")]
        Item649,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("650")]
        Item650,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("651")]
        Item651,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("652")]
        Item652,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("653")]
        Item653,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("654")]
        Item654,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("655")]
        Item655,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("656")]
        Item656,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("657")]
        Item657,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("658")]
        Item658,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("659")]
        Item659,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("700")]
        Item700,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("701")]
        Item701,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("702")]
        Item702,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("703")]
        Item703,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("704")]
        Item704,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("705")]
        Item705,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("706")]
        Item706,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("707")]
        Item707,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("708")]
        Item708,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("709")]
        Item709,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("710")]
        Item710,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("711")]
        Item711,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("712")]
        Item712,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("713")]
        Item713,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("714")]
        Item714,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("715")]
        Item715,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("716")]
        Item716,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("717")]
        Item717,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("718")]
        Item718,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("719")]
        Item719,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("720")]
        Item720,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("721")]
        Item721,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("722")]
        Item722,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("723")]
        Item723,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("724")]
        Item724,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("725")]
        Item725,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("726")]
        Item726,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("727")]
        Item727,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("728")]
        Item728,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("729")]
        Item729,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("730")]
        Item730,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("731")]
        Item731,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("732")]
        Item732,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("733")]
        Item733,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("734")]
        Item734,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("735")]
        Item735,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("736")]
        Item736,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("737")]
        Item737,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("738")]
        Item738,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("739")]
        Item739,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("740")]
        Item740,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("741")]
        Item741,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("742")]
        Item742,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("743")]
        Item743,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("744")]
        Item744,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("745")]
        Item745,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("746")]
        Item746,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("747")]
        Item747,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("748")]
        Item748,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("749")]
        Item749,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("750")]
        Item750,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("751")]
        Item751,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("760")]
        Item760,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("761")]
        Item761,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("763")]
        Item763,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("764")]
        Item764,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("765")]
        Item765,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("766")]
        Item766,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("770")]
        Item770,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("775")]
        Item775,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("780")]
        Item780,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("781")]
        Item781,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("782")]
        Item782,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("783")]
        Item783,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("784")]
        Item784,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("785")]
        Item785,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("786")]
        Item786,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("787")]
        Item787,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("788")]
        Item788,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("789")]
        Item789,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("790")]
        Item790,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("791")]
        Item791,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("792")]
        Item792,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("793")]
        Item793,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("794")]
        Item794,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("795")]
        Item795,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("796")]
        Item796,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("797")]
        Item797,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("798")]
        Item798,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("799")]
        Item799,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("810")]
        Item810,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("811")]
        Item811,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("812")]
        Item812,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("820")]
        Item820,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("821")]
        Item821,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("822")]
        Item822,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("823")]
        Item823,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("824")]
        Item824,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("825")]
        Item825,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("830")]
        Item830,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("833")]
        Item833,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("840")]
        Item840,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("841")]
        Item841,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("850")]
        Item850,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("851")]
        Item851,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("852")]
        Item852,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("853")]
        Item853,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("855")]
        Item855,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("856")]
        Item856,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("860")]
        Item860,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("861")]
        Item861,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("862")]
        Item862,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("863")]
        Item863,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("864")]
        Item864,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("865")]
        Item865,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("870")]
        Item870,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("890")]
        Item890,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("895")]
        Item895,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("896")]
        Item896,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("901")]
        Item901,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("910")]
        Item910,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("911")]
        Item911,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("913")]
        Item913,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("914")]
        Item914,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("915")]
        Item915,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("916")]
        Item916,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("917")]
        Item917,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("925")]
        Item925,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("926")]
        Item926,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("927")]
        Item927,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("929")]
        Item929,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("930")]
        Item930,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("931")]
        Item931,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("932")]
        Item932,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("933")]
        Item933,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("934")]
        Item934,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("935")]
        Item935,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("936")]
        Item936,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("937")]
        Item937,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("938")]
        Item938,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("940")]
        Item940,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("941")]
        Item941,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("950")]
        Item950,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("951")]
        Item951,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("952")]
        Item952,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("953")]
        Item953,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("954")]
        Item954,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("955")]
        Item955,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("960")]
        Item960,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("961")]
        Item961,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("962")]
        Item962,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("963")]
        Item963,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("964")]
        Item964,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("965")]
        Item965,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("966")]
        Item966,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("970")]
        Item970,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("971")]
        Item971,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("972")]
        Item972,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("974")]
        Item974,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("975")]
        Item975,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("976")]
        Item976,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("977")]
        Item977,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("978")]
        Item978,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("979")]
        Item979,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("990")]
        Item990,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("991")]
        Item991,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("995")]
        Item995,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("996")]
        Item996,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("998")]
        Item998,
    }
}