//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/base/v03")]
    public partial class ProductQuantityEnhancedType
    {
        private string certificateLineNumberField;
        private string cnCodeField;
        private string commodityCodeTARICCodeField;
        private MassQuantityType netWeightMeasureField;
        private SupplementaryQuantityType supplementaryUnitsField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
        public string CertificateLineNumber
        {
            get
            {
                return this.certificateLineNumberField;
            }

            set
            {
                this.certificateLineNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string CnCode
        {
            get
            {
                return this.cnCodeField;
            }

            set
            {
                this.cnCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string CommodityCodeTARICCode
        {
            get
            {
                return this.commodityCodeTARICCodeField;
            }

            set
            {
                this.commodityCodeTARICCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public MassQuantityType NetWeightMeasure
        {
            get
            {
                return this.netWeightMeasureField;
            }

            set
            {
                this.netWeightMeasureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public SupplementaryQuantityType SupplementaryUnits
        {
            get
            {
                return this.supplementaryUnitsField;
            }

            set
            {
                this.supplementaryUnitsField = value;
            }
        }
    }
}