//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:un:unece:uncefact:codelist:standard:UNECE:ReferenceTypeCode:D16B")]
    public enum ReferenceTypeCodeContentType
    {
        /// <remarks/>
        AAA,
        /// <remarks/>
        AAB,
        /// <remarks/>
        AAC,
        /// <remarks/>
        AAD,
        /// <remarks/>
        AAE,
        /// <remarks/>
        AAF,
        /// <remarks/>
        AAG,
        /// <remarks/>
        AAH,
        /// <remarks/>
        AAI,
        /// <remarks/>
        AAJ,
        /// <remarks/>
        AAK,
        /// <remarks/>
        AAL,
        /// <remarks/>
        AAM,
        /// <remarks/>
        AAN,
        /// <remarks/>
        AAO,
        /// <remarks/>
        AAP,
        /// <remarks/>
        AAQ,
        /// <remarks/>
        AAR,
        /// <remarks/>
        AAS,
        /// <remarks/>
        AAT,
        /// <remarks/>
        AAU,
        /// <remarks/>
        AAV,
        /// <remarks/>
        AAW,
        /// <remarks/>
        AAX,
        /// <remarks/>
        AAY,
        /// <remarks/>
        AAZ,
        /// <remarks/>
        ABA,
        /// <remarks/>
        ABB,
        /// <remarks/>
        ABC,
        /// <remarks/>
        ABD,
        /// <remarks/>
        ABE,
        /// <remarks/>
        ABF,
        /// <remarks/>
        ABG,
        /// <remarks/>
        ABH,
        /// <remarks/>
        ABI,
        /// <remarks/>
        ABJ,
        /// <remarks/>
        ABK,
        /// <remarks/>
        ABL,
        /// <remarks/>
        ABM,
        /// <remarks/>
        ABN,
        /// <remarks/>
        ABO,
        /// <remarks/>
        ABP,
        /// <remarks/>
        ABQ,
        /// <remarks/>
        ABR,
        /// <remarks/>
        ABS,
        /// <remarks/>
        ABT,
        /// <remarks/>
        ABU,
        /// <remarks/>
        ABV,
        /// <remarks/>
        ABW,
        /// <remarks/>
        ABX,
        /// <remarks/>
        ABY,
        /// <remarks/>
        ABZ,
        /// <remarks/>
        AC,
        /// <remarks/>
        ACA,
        /// <remarks/>
        ACB,
        /// <remarks/>
        ACC,
        /// <remarks/>
        ACD,
        /// <remarks/>
        ACE,
        /// <remarks/>
        ACF,
        /// <remarks/>
        ACG,
        /// <remarks/>
        ACH,
        /// <remarks/>
        ACI,
        /// <remarks/>
        ACJ,
        /// <remarks/>
        ACK,
        /// <remarks/>
        ACL,
        /// <remarks/>
        ACN,
        /// <remarks/>
        ACO,
        /// <remarks/>
        ACP,
        /// <remarks/>
        ACQ,
        /// <remarks/>
        ACR,
        /// <remarks/>
        ACT,
        /// <remarks/>
        ACU,
        /// <remarks/>
        ACV,
        /// <remarks/>
        ACW,
        /// <remarks/>
        ACX,
        /// <remarks/>
        ACY,
        /// <remarks/>
        ACZ,
        /// <remarks/>
        ADA,
        /// <remarks/>
        ADB,
        /// <remarks/>
        ADC,
        /// <remarks/>
        ADD,
        /// <remarks/>
        ADE,
        /// <remarks/>
        ADF,
        /// <remarks/>
        ADG,
        /// <remarks/>
        ADI,
        /// <remarks/>
        ADJ,
        /// <remarks/>
        ADK,
        /// <remarks/>
        ADL,
        /// <remarks/>
        ADM,
        /// <remarks/>
        ADN,
        /// <remarks/>
        ADO,
        /// <remarks/>
        ADP,
        /// <remarks/>
        ADQ,
        /// <remarks/>
        ADT,
        /// <remarks/>
        ADU,
        /// <remarks/>
        ADV,
        /// <remarks/>
        ADW,
        /// <remarks/>
        ADX,
        /// <remarks/>
        ADY,
        /// <remarks/>
        ADZ,
        /// <remarks/>
        AE,
        /// <remarks/>
        AEA,
        /// <remarks/>
        AEB,
        /// <remarks/>
        AEC,
        /// <remarks/>
        AED,
        /// <remarks/>
        AEE,
        /// <remarks/>
        AEF,
        /// <remarks/>
        AEG,
        /// <remarks/>
        AEH,
        /// <remarks/>
        AEI,
        /// <remarks/>
        AEJ,
        /// <remarks/>
        AEK,
        /// <remarks/>
        AEL,
        /// <remarks/>
        AEM,
        /// <remarks/>
        AEN,
        /// <remarks/>
        AEO,
        /// <remarks/>
        AEP,
        /// <remarks/>
        AEQ,
        /// <remarks/>
        AER,
        /// <remarks/>
        AES,
        /// <remarks/>
        AET,
        /// <remarks/>
        AEU,
        /// <remarks/>
        AEV,
        /// <remarks/>
        AEW,
        /// <remarks/>
        AEX,
        /// <remarks/>
        AEY,
        /// <remarks/>
        AEZ,
        /// <remarks/>
        AF,
        /// <remarks/>
        AFA,
        /// <remarks/>
        AFB,
        /// <remarks/>
        AFC,
        /// <remarks/>
        AFD,
        /// <remarks/>
        AFE,
        /// <remarks/>
        AFF,
        /// <remarks/>
        AFG,
        /// <remarks/>
        AFH,
        /// <remarks/>
        AFI,
        /// <remarks/>
        AFJ,
        /// <remarks/>
        AFK,
        /// <remarks/>
        AFL,
        /// <remarks/>
        AFM,
        /// <remarks/>
        AFN,
        /// <remarks/>
        AFO,
        /// <remarks/>
        AFP,
        /// <remarks/>
        AFQ,
        /// <remarks/>
        AFR,
        /// <remarks/>
        AFS,
        /// <remarks/>
        AFT,
        /// <remarks/>
        AFU,
        /// <remarks/>
        AFV,
        /// <remarks/>
        AFW,
        /// <remarks/>
        AFX,
        /// <remarks/>
        AFY,
        /// <remarks/>
        AFZ,
        /// <remarks/>
        AGA,
        /// <remarks/>
        AGB,
        /// <remarks/>
        AGC,
        /// <remarks/>
        AGD,
        /// <remarks/>
        AGE,
        /// <remarks/>
        AGF,
        /// <remarks/>
        AGG,
        /// <remarks/>
        AGH,
        /// <remarks/>
        AGI,
        /// <remarks/>
        AGJ,
        /// <remarks/>
        AGK,
        /// <remarks/>
        AGL,
        /// <remarks/>
        AGM,
        /// <remarks/>
        AGN,
        /// <remarks/>
        AGO,
        /// <remarks/>
        AGP,
        /// <remarks/>
        AGQ,
        /// <remarks/>
        AGR,
        /// <remarks/>
        AGS,
        /// <remarks/>
        AGT,
        /// <remarks/>
        AGU,
        /// <remarks/>
        AGV,
        /// <remarks/>
        AGW,
        /// <remarks/>
        AGX,
        /// <remarks/>
        AGY,
        /// <remarks/>
        AGZ,
        /// <remarks/>
        AHA,
        /// <remarks/>
        AHB,
        /// <remarks/>
        AHC,
        /// <remarks/>
        AHD,
        /// <remarks/>
        AHE,
        /// <remarks/>
        AHF,
        /// <remarks/>
        AHG,
        /// <remarks/>
        AHH,
        /// <remarks/>
        AHI,
        /// <remarks/>
        AHJ,
        /// <remarks/>
        AHK,
        /// <remarks/>
        AHL,
        /// <remarks/>
        AHM,
        /// <remarks/>
        AHN,
        /// <remarks/>
        AHO,
        /// <remarks/>
        AHP,
        /// <remarks/>
        AHQ,
        /// <remarks/>
        AHR,
        /// <remarks/>
        AHS,
        /// <remarks/>
        AHT,
        /// <remarks/>
        AHU,
        /// <remarks/>
        AHV,
        /// <remarks/>
        AHX,
        /// <remarks/>
        AHY,
        /// <remarks/>
        AHZ,
        /// <remarks/>
        AIA,
        /// <remarks/>
        AIB,
        /// <remarks/>
        AIC,
        /// <remarks/>
        AID,
        /// <remarks/>
        AIE,
        /// <remarks/>
        AIF,
        /// <remarks/>
        AIG,
        /// <remarks/>
        AIH,
        /// <remarks/>
        AII,
        /// <remarks/>
        AIJ,
        /// <remarks/>
        AIK,
        /// <remarks/>
        AIL,
        /// <remarks/>
        AIM,
        /// <remarks/>
        AIN,
        /// <remarks/>
        AIO,
        /// <remarks/>
        AIP,
        /// <remarks/>
        AIQ,
        /// <remarks/>
        AIR,
        /// <remarks/>
        AIS,
        /// <remarks/>
        AIT,
        /// <remarks/>
        AIU,
        /// <remarks/>
        AIV,
        /// <remarks/>
        AIW,
        /// <remarks/>
        AIX,
        /// <remarks/>
        AIY,
        /// <remarks/>
        AIZ,
        /// <remarks/>
        AJA,
        /// <remarks/>
        AJB,
        /// <remarks/>
        AJC,
        /// <remarks/>
        AJD,
        /// <remarks/>
        AJE,
        /// <remarks/>
        AJF,
        /// <remarks/>
        AJG,
        /// <remarks/>
        AJH,
        /// <remarks/>
        AJI,
        /// <remarks/>
        AJJ,
        /// <remarks/>
        AJK,
        /// <remarks/>
        AJL,
        /// <remarks/>
        AJM,
        /// <remarks/>
        AJN,
        /// <remarks/>
        AJO,
        /// <remarks/>
        AJP,
        /// <remarks/>
        AJQ,
        /// <remarks/>
        AJR,
        /// <remarks/>
        AJS,
        /// <remarks/>
        AJT,
        /// <remarks/>
        AJU,
        /// <remarks/>
        AJV,
        /// <remarks/>
        AJW,
        /// <remarks/>
        AJX,
        /// <remarks/>
        AJY,
        /// <remarks/>
        AJZ,
        /// <remarks/>
        AKA,
        /// <remarks/>
        AKB,
        /// <remarks/>
        AKC,
        /// <remarks/>
        AKD,
        /// <remarks/>
        AKE,
        /// <remarks/>
        AKF,
        /// <remarks/>
        AKG,
        /// <remarks/>
        AKH,
        /// <remarks/>
        AKI,
        /// <remarks/>
        AKJ,
        /// <remarks/>
        AKK,
        /// <remarks/>
        AKL,
        /// <remarks/>
        AKM,
        /// <remarks/>
        AKN,
        /// <remarks/>
        AKO,
        /// <remarks/>
        AKP,
        /// <remarks/>
        AKQ,
        /// <remarks/>
        AKR,
        /// <remarks/>
        AKS,
        /// <remarks/>
        AKT,
        /// <remarks/>
        AKU,
        /// <remarks/>
        AKV,
        /// <remarks/>
        AKW,
        /// <remarks/>
        AKX,
        /// <remarks/>
        AKY,
        /// <remarks/>
        AKZ,
        /// <remarks/>
        ALA,
        /// <remarks/>
        ALB,
        /// <remarks/>
        ALC,
        /// <remarks/>
        ALD,
        /// <remarks/>
        ALE,
        /// <remarks/>
        ALF,
        /// <remarks/>
        ALG,
        /// <remarks/>
        ALH,
        /// <remarks/>
        ALI,
        /// <remarks/>
        ALJ,
        /// <remarks/>
        ALK,
        /// <remarks/>
        ALL,
        /// <remarks/>
        ALM,
        /// <remarks/>
        ALN,
        /// <remarks/>
        ALO,
        /// <remarks/>
        ALP,
        /// <remarks/>
        ALQ,
        /// <remarks/>
        ALR,
        /// <remarks/>
        ALS,
        /// <remarks/>
        ALT,
        /// <remarks/>
        ALU,
        /// <remarks/>
        ALV,
        /// <remarks/>
        ALW,
        /// <remarks/>
        ALX,
        /// <remarks/>
        ALY,
        /// <remarks/>
        ALZ,
        /// <remarks/>
        AMA,
        /// <remarks/>
        AMB,
        /// <remarks/>
        AMC,
        /// <remarks/>
        AMD,
        /// <remarks/>
        AME,
        /// <remarks/>
        AMF,
        /// <remarks/>
        AMG,
        /// <remarks/>
        AMH,
        /// <remarks/>
        AMI,
        /// <remarks/>
        AMJ,
        /// <remarks/>
        AMK,
        /// <remarks/>
        AML,
        /// <remarks/>
        AMM,
        /// <remarks/>
        AMN,
        /// <remarks/>
        AMO,
        /// <remarks/>
        AMP,
        /// <remarks/>
        AMQ,
        /// <remarks/>
        AMR,
        /// <remarks/>
        AMS,
        /// <remarks/>
        AMT,
        /// <remarks/>
        AMU,
        /// <remarks/>
        AMV,
        /// <remarks/>
        AMW,
        /// <remarks/>
        AMX,
        /// <remarks/>
        AMY,
        /// <remarks/>
        AMZ,
        /// <remarks/>
        ANA,
        /// <remarks/>
        ANB,
        /// <remarks/>
        ANC,
        /// <remarks/>
        AND,
        /// <remarks/>
        ANE,
        /// <remarks/>
        ANF,
        /// <remarks/>
        ANG,
        /// <remarks/>
        ANH,
        /// <remarks/>
        ANI,
        /// <remarks/>
        ANJ,
        /// <remarks/>
        ANK,
        /// <remarks/>
        ANL,
        /// <remarks/>
        ANM,
        /// <remarks/>
        ANN,
        /// <remarks/>
        ANO,
        /// <remarks/>
        ANP,
        /// <remarks/>
        ANQ,
        /// <remarks/>
        ANR,
        /// <remarks/>
        ANS,
        /// <remarks/>
        ANT,
        /// <remarks/>
        ANU,
        /// <remarks/>
        ANV,
        /// <remarks/>
        ANW,
        /// <remarks/>
        ANX,
        /// <remarks/>
        ANY,
        /// <remarks/>
        AOA,
        /// <remarks/>
        AOD,
        /// <remarks/>
        AOE,
        /// <remarks/>
        AOF,
        /// <remarks/>
        AOG,
        /// <remarks/>
        AOH,
        /// <remarks/>
        AOI,
        /// <remarks/>
        AOJ,
        /// <remarks/>
        AOK,
        /// <remarks/>
        AOL,
        /// <remarks/>
        AOM,
        /// <remarks/>
        AON,
        /// <remarks/>
        AOO,
        /// <remarks/>
        AOP,
        /// <remarks/>
        AOQ,
        /// <remarks/>
        AOR,
        /// <remarks/>
        AOS,
        /// <remarks/>
        AOT,
        /// <remarks/>
        AOU,
        /// <remarks/>
        AOV,
        /// <remarks/>
        AOW,
        /// <remarks/>
        AOX,
        /// <remarks/>
        AOY,
        /// <remarks/>
        AOZ,
        /// <remarks/>
        AP,
        /// <remarks/>
        APA,
        /// <remarks/>
        APB,
        /// <remarks/>
        APC,
        /// <remarks/>
        APD,
        /// <remarks/>
        APE,
        /// <remarks/>
        APF,
        /// <remarks/>
        APG,
        /// <remarks/>
        APH,
        /// <remarks/>
        API,
        /// <remarks/>
        APJ,
        /// <remarks/>
        APK,
        /// <remarks/>
        APL,
        /// <remarks/>
        APM,
        /// <remarks/>
        APN,
        /// <remarks/>
        APO,
        /// <remarks/>
        APP,
        /// <remarks/>
        APQ,
        /// <remarks/>
        APR,
        /// <remarks/>
        APS,
        /// <remarks/>
        APT,
        /// <remarks/>
        APU,
        /// <remarks/>
        APV,
        /// <remarks/>
        APW,
        /// <remarks/>
        APX,
        /// <remarks/>
        APY,
        /// <remarks/>
        APZ,
        /// <remarks/>
        AQA,
        /// <remarks/>
        AQB,
        /// <remarks/>
        AQC,
        /// <remarks/>
        AQD,
        /// <remarks/>
        AQE,
        /// <remarks/>
        AQF,
        /// <remarks/>
        AQG,
        /// <remarks/>
        AQH,
        /// <remarks/>
        AQI,
        /// <remarks/>
        AQJ,
        /// <remarks/>
        AQK,
        /// <remarks/>
        AQL,
        /// <remarks/>
        AQM,
        /// <remarks/>
        AQN,
        /// <remarks/>
        AQO,
        /// <remarks/>
        AQP,
        /// <remarks/>
        AQQ,
        /// <remarks/>
        AQR,
        /// <remarks/>
        AQS,
        /// <remarks/>
        AQT,
        /// <remarks/>
        AQU,
        /// <remarks/>
        AQV,
        /// <remarks/>
        AQW,
        /// <remarks/>
        AQX,
        /// <remarks/>
        AQY,
        /// <remarks/>
        AQZ,
        /// <remarks/>
        ARA,
        /// <remarks/>
        ARB,
        /// <remarks/>
        ARC,
        /// <remarks/>
        ARD,
        /// <remarks/>
        ARE,
        /// <remarks/>
        ARF,
        /// <remarks/>
        ARG,
        /// <remarks/>
        ARH,
        /// <remarks/>
        ARI,
        /// <remarks/>
        ARJ,
        /// <remarks/>
        ARK,
        /// <remarks/>
        ARL,
        /// <remarks/>
        ARM,
        /// <remarks/>
        ARN,
        /// <remarks/>
        ARO,
        /// <remarks/>
        ARP,
        /// <remarks/>
        ARQ,
        /// <remarks/>
        ARR,
        /// <remarks/>
        ARS,
        /// <remarks/>
        ART,
        /// <remarks/>
        ARU,
        /// <remarks/>
        ARV,
        /// <remarks/>
        ARW,
        /// <remarks/>
        ARX,
        /// <remarks/>
        ARY,
        /// <remarks/>
        ARZ,
        /// <remarks/>
        ASA,
        /// <remarks/>
        ASB,
        /// <remarks/>
        ASC,
        /// <remarks/>
        ASD,
        /// <remarks/>
        ASE,
        /// <remarks/>
        ASF,
        /// <remarks/>
        ASG,
        /// <remarks/>
        ASH,
        /// <remarks/>
        ASI,
        /// <remarks/>
        ASJ,
        /// <remarks/>
        ASK,
        /// <remarks/>
        ASL,
        /// <remarks/>
        ASM,
        /// <remarks/>
        ASN,
        /// <remarks/>
        ASO,
        /// <remarks/>
        ASP,
        /// <remarks/>
        ASQ,
        /// <remarks/>
        ASR,
        /// <remarks/>
        ASS,
        /// <remarks/>
        AST,
        /// <remarks/>
        ASU,
        /// <remarks/>
        ASV,
        /// <remarks/>
        ASW,
        /// <remarks/>
        ASX,
        /// <remarks/>
        ASY,
        /// <remarks/>
        ASZ,
        /// <remarks/>
        ATA,
        /// <remarks/>
        ATB,
        /// <remarks/>
        ATC,
        /// <remarks/>
        ATD,
        /// <remarks/>
        ATE,
        /// <remarks/>
        ATF,
        /// <remarks/>
        ATG,
        /// <remarks/>
        ATH,
        /// <remarks/>
        ATI,
        /// <remarks/>
        ATJ,
        /// <remarks/>
        ATK,
        /// <remarks/>
        ATL,
        /// <remarks/>
        ATM,
        /// <remarks/>
        ATN,
        /// <remarks/>
        ATO,
        /// <remarks/>
        ATP,
        /// <remarks/>
        ATQ,
        /// <remarks/>
        ATR,
        /// <remarks/>
        ATS,
        /// <remarks/>
        ATT,
        /// <remarks/>
        ATU,
        /// <remarks/>
        ATV,
        /// <remarks/>
        ATW,
        /// <remarks/>
        ATX,
        /// <remarks/>
        ATY,
        /// <remarks/>
        ATZ,
        /// <remarks/>
        AU,
        /// <remarks/>
        AUA,
        /// <remarks/>
        AUB,
        /// <remarks/>
        AUC,
        /// <remarks/>
        AUD,
        /// <remarks/>
        AUE,
        /// <remarks/>
        AUF,
        /// <remarks/>
        AUG,
        /// <remarks/>
        AUH,
        /// <remarks/>
        AUI,
        /// <remarks/>
        AUJ,
        /// <remarks/>
        AUK,
        /// <remarks/>
        AUL,
        /// <remarks/>
        AUM,
        /// <remarks/>
        AUN,
        /// <remarks/>
        AUO,
        /// <remarks/>
        AUP,
        /// <remarks/>
        AUQ,
        /// <remarks/>
        AUR,
        /// <remarks/>
        AUS,
        /// <remarks/>
        AUT,
        /// <remarks/>
        AUU,
        /// <remarks/>
        AUV,
        /// <remarks/>
        AUW,
        /// <remarks/>
        AUX,
        /// <remarks/>
        AUY,
        /// <remarks/>
        AUZ,
        /// <remarks/>
        AV,
        /// <remarks/>
        AVA,
        /// <remarks/>
        AVB,
        /// <remarks/>
        AVC,
        /// <remarks/>
        AVD,
        /// <remarks/>
        AVE,
        /// <remarks/>
        AVF,
        /// <remarks/>
        AVG,
        /// <remarks/>
        AVH,
        /// <remarks/>
        AVI,
        /// <remarks/>
        AVJ,
        /// <remarks/>
        AVK,
        /// <remarks/>
        AVL,
        /// <remarks/>
        AVM,
        /// <remarks/>
        AVN,
        /// <remarks/>
        AVO,
        /// <remarks/>
        AVP,
        /// <remarks/>
        AVQ,
        /// <remarks/>
        AVR,
        /// <remarks/>
        AVS,
        /// <remarks/>
        AVT,
        /// <remarks/>
        AVU,
        /// <remarks/>
        AVV,
        /// <remarks/>
        AVW,
        /// <remarks/>
        AVX,
        /// <remarks/>
        AVY,
        /// <remarks/>
        AVZ,
        /// <remarks/>
        AWA,
        /// <remarks/>
        AWB,
        /// <remarks/>
        AWC,
        /// <remarks/>
        AWD,
        /// <remarks/>
        AWE,
        /// <remarks/>
        AWF,
        /// <remarks/>
        AWG,
        /// <remarks/>
        AWH,
        /// <remarks/>
        AWI,
        /// <remarks/>
        AWJ,
        /// <remarks/>
        AWK,
        /// <remarks/>
        AWL,
        /// <remarks/>
        AWM,
        /// <remarks/>
        AWN,
        /// <remarks/>
        AWO,
        /// <remarks/>
        AWP,
        /// <remarks/>
        AWQ,
        /// <remarks/>
        AWR,
        /// <remarks/>
        AWS,
        /// <remarks/>
        AWT,
        /// <remarks/>
        AWU,
        /// <remarks/>
        AWV,
        /// <remarks/>
        AWW,
        /// <remarks/>
        AWX,
        /// <remarks/>
        AWY,
        /// <remarks/>
        AWZ,
        /// <remarks/>
        AXA,
        /// <remarks/>
        AXB,
        /// <remarks/>
        AXC,
        /// <remarks/>
        AXD,
        /// <remarks/>
        AXE,
        /// <remarks/>
        AXF,
        /// <remarks/>
        AXG,
        /// <remarks/>
        AXH,
        /// <remarks/>
        AXI,
        /// <remarks/>
        AXJ,
        /// <remarks/>
        AXK,
        /// <remarks/>
        AXL,
        /// <remarks/>
        AXM,
        /// <remarks/>
        AXN,
        /// <remarks/>
        AXO,
        /// <remarks/>
        AXP,
        /// <remarks/>
        AXQ,
        /// <remarks/>
        AXR,
        /// <remarks/>
        BA,
        /// <remarks/>
        BC,
        /// <remarks/>
        BD,
        /// <remarks/>
        BE,
        /// <remarks/>
        BH,
        /// <remarks/>
        BM,
        /// <remarks/>
        BN,
        /// <remarks/>
        BO,
        /// <remarks/>
        BR,
        /// <remarks/>
        BT,
        /// <remarks/>
        BW,
        /// <remarks/>
        CAS,
        /// <remarks/>
        CAT,
        /// <remarks/>
        CAU,
        /// <remarks/>
        CAV,
        /// <remarks/>
        CAW,
        /// <remarks/>
        CAX,
        /// <remarks/>
        CAY,
        /// <remarks/>
        CAZ,
        /// <remarks/>
        CBA,
        /// <remarks/>
        CBB,
        /// <remarks/>
        CD,
        /// <remarks/>
        CEC,
        /// <remarks/>
        CED,
        /// <remarks/>
        CFE,
        /// <remarks/>
        CFF,
        /// <remarks/>
        CFO,
        /// <remarks/>
        CG,
        /// <remarks/>
        CH,
        /// <remarks/>
        CK,
        /// <remarks/>
        CKN,
        /// <remarks/>
        CM,
        /// <remarks/>
        CMR,
        /// <remarks/>
        CN,
        /// <remarks/>
        CNO,
        /// <remarks/>
        COF,
        /// <remarks/>
        CP,
        /// <remarks/>
        CR,
        /// <remarks/>
        CRN,
        /// <remarks/>
        CS,
        /// <remarks/>
        CST,
        /// <remarks/>
        CT,
        /// <remarks/>
        CU,
        /// <remarks/>
        CV,
        /// <remarks/>
        CW,
        /// <remarks/>
        CZ,
        /// <remarks/>
        DA,
        /// <remarks/>
        DAN,
        /// <remarks/>
        DB,
        /// <remarks/>
        DI,
        /// <remarks/>
        DL,
        /// <remarks/>
        DM,
        /// <remarks/>
        DQ,
        /// <remarks/>
        DR,
        /// <remarks/>
        EA,
        /// <remarks/>
        EB,
        /// <remarks/>
        ED,
        /// <remarks/>
        EE,
        /// <remarks/>
        EI,
        /// <remarks/>
        EN,
        /// <remarks/>
        EQ,
        /// <remarks/>
        ER,
        /// <remarks/>
        ERN,
        /// <remarks/>
        ET,
        /// <remarks/>
        EX,
        /// <remarks/>
        FC,
        /// <remarks/>
        FF,
        /// <remarks/>
        FI,
        /// <remarks/>
        FLW,
        /// <remarks/>
        FN,
        /// <remarks/>
        FO,
        /// <remarks/>
        FS,
        /// <remarks/>
        FT,
        /// <remarks/>
        FV,
        /// <remarks/>
        FX,
        /// <remarks/>
        GA,
        /// <remarks/>
        GC,
        /// <remarks/>
        GD,
        /// <remarks/>
        GDN,
        /// <remarks/>
        GN,
        /// <remarks/>
        HS,
        /// <remarks/>
        HWB,
        /// <remarks/>
        IA,
        /// <remarks/>
        IB,
        /// <remarks/>
        ICA,
        /// <remarks/>
        ICE,
        /// <remarks/>
        ICO,
        /// <remarks/>
        II,
        /// <remarks/>
        IL,
        /// <remarks/>
        INB,
        /// <remarks/>
        INN,
        /// <remarks/>
        INO,
        /// <remarks/>
        IP,
        /// <remarks/>
        IS,
        /// <remarks/>
        IT,
        /// <remarks/>
        IV,
        /// <remarks/>
        JB,
        /// <remarks/>
        JE,
        /// <remarks/>
        LA,
        /// <remarks/>
        LAN,
        /// <remarks/>
        LAR,
        /// <remarks/>
        LB,
        /// <remarks/>
        LC,
        /// <remarks/>
        LI,
        /// <remarks/>
        LO,
        /// <remarks/>
        LRC,
        /// <remarks/>
        LS,
        /// <remarks/>
        MA,
        /// <remarks/>
        MB,
        /// <remarks/>
        MF,
        /// <remarks/>
        MG,
        /// <remarks/>
        MH,
        /// <remarks/>
        MR,
        /// <remarks/>
        MRN,
        /// <remarks/>
        MS,
        /// <remarks/>
        MSS,
        /// <remarks/>
        MWB,
        /// <remarks/>
        NA,
        /// <remarks/>
        NF,
        /// <remarks/>
        OH,
        /// <remarks/>
        OI,
        /// <remarks/>
        ON,
        /// <remarks/>
        OP,
        /// <remarks/>
        OR,
        /// <remarks/>
        PB,
        /// <remarks/>
        PC,
        /// <remarks/>
        PD,
        /// <remarks/>
        PE,
        /// <remarks/>
        PF,
        /// <remarks/>
        PI,
        /// <remarks/>
        PK,
        /// <remarks/>
        PL,
        /// <remarks/>
        POR,
        /// <remarks/>
        PP,
        /// <remarks/>
        PQ,
        /// <remarks/>
        PR,
        /// <remarks/>
        PS,
        /// <remarks/>
        PW,
        /// <remarks/>
        PY,
        /// <remarks/>
        RA,
        /// <remarks/>
        RC,
        /// <remarks/>
        RCN,
        /// <remarks/>
        RE,
        /// <remarks/>
        REN,
        /// <remarks/>
        RF,
        /// <remarks/>
        RR,
        /// <remarks/>
        RT,
        /// <remarks/>
        SA,
        /// <remarks/>
        SB,
        /// <remarks/>
        SD,
        /// <remarks/>
        SE,
        /// <remarks/>
        SEA,
        /// <remarks/>
        SF,
        /// <remarks/>
        SH,
        /// <remarks/>
        SI,
        /// <remarks/>
        SM,
        /// <remarks/>
        SN,
        /// <remarks/>
        SP,
        /// <remarks/>
        SQ,
        /// <remarks/>
        SRN,
        /// <remarks/>
        SS,
        /// <remarks/>
        STA,
        /// <remarks/>
        SW,
        /// <remarks/>
        SZ,
        /// <remarks/>
        TB,
        /// <remarks/>
        TCR,
        /// <remarks/>
        TE,
        /// <remarks/>
        TF,
        /// <remarks/>
        TI,
        /// <remarks/>
        TIN,
        /// <remarks/>
        TL,
        /// <remarks/>
        TN,
        /// <remarks/>
        TP,
        /// <remarks/>
        UAR,
        /// <remarks/>
        UC,
        /// <remarks/>
        UCN,
        /// <remarks/>
        UN,
        /// <remarks/>
        UO,
        /// <remarks/>
        URI,
        /// <remarks/>
        VA,
        /// <remarks/>
        VC,
        /// <remarks/>
        VGR,
        /// <remarks/>
        VM,
        /// <remarks/>
        VN,
        /// <remarks/>
        VON,
        /// <remarks/>
        VOR,
        /// <remarks/>
        VP,
        /// <remarks/>
        VR,
        /// <remarks/>
        VS,
        /// <remarks/>
        VT,
        /// <remarks/>
        VV,
        /// <remarks/>
        WE,
        /// <remarks/>
        WM,
        /// <remarks/>
        WN,
        /// <remarks/>
        WR,
        /// <remarks/>
        WS,
        /// <remarks/>
        WY,
        /// <remarks/>
        XA,
        /// <remarks/>
        XC,
        /// <remarks/>
        XP,
        /// <remarks/>
        ZZZ,
    }
}