//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:21" + "")]
    public partial class SPSCountrySubDivisionType
    {
        private IDType idField;
        private TextType[] nameField;
        private CodeType hierarchicalLevelCodeField;
        private LocationFunctionCodeType functionTypeCodeField;
        private SPSCountrySubDivisionType[] superordinateSPSCountrySubDivisionField;
        private SPSCountrySubDivisionType[] subordinateSPSCountrySubDivisionField;
        private SPSPartyType[] activityAuthorizedSPSPartyField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public IDType ID
        {
            get
            {
                return this.idField;
            }

            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Name", Order = 1)]
        public TextType[] Name
        {
            get
            {
                return this.nameField;
            }

            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public CodeType HierarchicalLevelCode
        {
            get
            {
                return this.hierarchicalLevelCodeField;
            }

            set
            {
                this.hierarchicalLevelCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public LocationFunctionCodeType FunctionTypeCode
        {
            get
            {
                return this.functionTypeCodeField;
            }

            set
            {
                this.functionTypeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SuperordinateSPSCountrySubDivision", Order = 4)]
        public SPSCountrySubDivisionType[] SuperordinateSPSCountrySubDivision
        {
            get
            {
                return this.superordinateSPSCountrySubDivisionField;
            }

            set
            {
                this.superordinateSPSCountrySubDivisionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubordinateSPSCountrySubDivision", Order = 5)]
        public SPSCountrySubDivisionType[] SubordinateSPSCountrySubDivision
        {
            get
            {
                return this.subordinateSPSCountrySubDivisionField;
            }

            set
            {
                this.subordinateSPSCountrySubDivisionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActivityAuthorizedSPSParty", Order = 6)]
        public SPSPartyType[] ActivityAuthorizedSPSParty
        {
            get
            {
                return this.activityAuthorizedSPSPartyField;
            }

            set
            {
                this.activityAuthorizedSPSPartyField = value;
            }
        }
    }
}