//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:21" + "")]
    public partial class SPSProcessCharacteristicType
    {
        private MeasuredAttributeCodeType typeCodeField;
        private TextType[] descriptionField;
        private MeasureType valueMeasureField;
        private MeasureType minimumValueMeasureField;
        private MeasureType maximumValueMeasureField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public MeasuredAttributeCodeType TypeCode
        {
            get
            {
                return this.typeCodeField;
            }

            set
            {
                this.typeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description", Order = 1)]
        public TextType[] Description
        {
            get
            {
                return this.descriptionField;
            }

            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public MeasureType ValueMeasure
        {
            get
            {
                return this.valueMeasureField;
            }

            set
            {
                this.valueMeasureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public MeasureType MinimumValueMeasure
        {
            get
            {
                return this.minimumValueMeasureField;
            }

            set
            {
                this.minimumValueMeasureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public MeasureType MaximumValueMeasure
        {
            get
            {
                return this.maximumValueMeasureField;
            }

            set
            {
                this.maximumValueMeasureField = value;
            }
        }
    }
}