//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:21" + "")]
    public partial class SPSReferencedDocumentType
    {
        private string issueDateTimeField;
        private DocumentCodeType typeCodeField;
        private ReferenceCodeType relationshipTypeCodeField;
        private IDType idField;
        private BinaryObjectType[] attachmentBinaryObjectField;
        private TextType informationField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string IssueDateTime
        {
            get
            {
                return this.issueDateTimeField;
            }

            set
            {
                this.issueDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public DocumentCodeType TypeCode
        {
            get
            {
                return this.typeCodeField;
            }

            set
            {
                this.typeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public ReferenceCodeType RelationshipTypeCode
        {
            get
            {
                return this.relationshipTypeCodeField;
            }

            set
            {
                this.relationshipTypeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public IDType ID
        {
            get
            {
                return this.idField;
            }

            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttachmentBinaryObject", Order = 4)]
        public BinaryObjectType[] AttachmentBinaryObject
        {
            get
            {
                return this.attachmentBinaryObjectField;
            }

            set
            {
                this.attachmentBinaryObjectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public TextType Information
        {
            get
            {
                return this.informationField;
            }

            set
            {
                this.informationField = value;
            }
        }
    }
}