//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:21" + "")]
    public partial class SPSTransportEquipmentType
    {
        private IDType idField;
        private SPSSealType[] affixedSPSSealField;
        private SPSTemperatureType[] settingSPSTemperatureField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public IDType ID
        {
            get
            {
                return this.idField;
            }

            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AffixedSPSSeal", Order = 1)]
        public SPSSealType[] AffixedSPSSeal
        {
            get
            {
                return this.affixedSPSSealField;
            }

            set
            {
                this.affixedSPSSealField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SettingSPSTemperature", Order = 2)]
        public SPSTemperatureType[] SettingSPSTemperature
        {
            get
            {
                return this.settingSPSTemperatureField;
            }

            set
            {
                this.settingSPSTemperatureField = value;
            }
        }
    }
}