//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://ec.europa.eu/tracesnt/ws/impl/certificate/attachments/v1", ConfigurationName = "TracesNT.WebServices.CertificateAttachmentsPort")]
    public interface CertificateAttachmentsPort
    {
        [System.ServiceModel.OperationContractAttribute(Action = "getCertificateAttachment", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TracesNT.WebServices.CertificateAttachmentNotFoundExceptionType), Action = "getCertificateAttachment", Name = "CertificateAttachmentNotFoundException", Namespace = "http://ec.europa.eu/tracesnt/certificate/attachments/v1")]
        [System.ServiceModel.FaultContractAttribute(typeof(TracesNT.WebServices.PermissionDeniedExceptionType), Action = "getCertificateAttachment", Name = "CertificateAttachmentPermissionDeniedException", Namespace = "http://ec.europa.eu/tracesnt/certificate/attachments/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetCertificateAttachmentResponse> getCertificateAttachmentAsync(TracesNT.WebServices.GetCertificateAttachmentRequest request);
        [System.ServiceModel.OperationContractAttribute(Action = "submitCertificateAttachment", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TracesNT.WebServices.CertificateAttachmentSubmitExceptionType), Action = "submitCertificateAttachment", Name = "CertificateAttachmentSubmitException", Namespace = "http://ec.europa.eu/tracesnt/certificate/attachments/v1")]
        [System.ServiceModel.FaultContractAttribute(typeof(TracesNT.WebServices.PermissionDeniedExceptionType), Action = "submitCertificateAttachment", Name = "CertificateAttachmentPermissionDeniedException", Namespace = "http://ec.europa.eu/tracesnt/certificate/attachments/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TracesNT.WebServices.SubmitCertificateAttachmentResponse> submitCertificateAttachmentAsync(TracesNT.WebServices.SubmitCertificateAttachmentRequest request);
    }
}