//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://ec.europa.eu/tracesnt/ws/impl/certificate/euintra/v1", ConfigurationName = "TracesNT.WebServices.EuIntraCertificatePort")]
    public interface EuIntraCertificatePort
    {
        [System.ServiceModel.OperationContractAttribute(Action = "getEuIntraCertificate", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TracesNT.WebServices.EuIntraCertificateNotFoundExceptionType), Action = "getEuIntraCertificate", Name = "EuIntraCertificateNotFoundException", Namespace = "http://ec.europa.eu/tracesnt/certificate/euintra/v1")]
        [System.ServiceModel.FaultContractAttribute(typeof(TracesNT.WebServices.EuIntraCertificatePermissionDeniedExceptionType), Action = "getEuIntraCertificate", Name = "EuIntraCertificatePermissionDeniedException", Namespace = "http://ec.europa.eu/tracesnt/certificate/euintra/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetEuIntraCertificateResponse> getEuIntraCertificateAsync(TracesNT.WebServices.GetEuIntraCertificateRequest request);
        [System.ServiceModel.OperationContractAttribute(Action = "getEuIntraPdfCertificate", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TracesNT.WebServices.EuIntraCertificateNotFoundExceptionType), Action = "getEuIntraPdfCertificate", Name = "EuIntraCertificateNotFoundException", Namespace = "http://ec.europa.eu/tracesnt/certificate/euintra/v1")]
        [System.ServiceModel.FaultContractAttribute(typeof(TracesNT.WebServices.EuIntraCertificatePermissionDeniedExceptionType), Action = "getEuIntraPdfCertificate", Name = "EuIntraCertificatePermissionDeniedException", Namespace = "http://ec.europa.eu/tracesnt/certificate/euintra/v1")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action = "getEuIntraPdfCertificate", Name = "IllegalLanguageCodeException", Namespace = "http://ec.europa.eu/tracesnt/certificate/base/v01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetEuIntraPdfCertificateResponse> getEuIntraPdfCertificateAsync(TracesNT.WebServices.GetEuIntraPdfCertificateRequest request);
        [System.ServiceModel.OperationContractAttribute(Action = "getEuIntraSignedPdfCertificate", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TracesNT.WebServices.EuIntraCertificateNotFoundExceptionType), Action = "getEuIntraSignedPdfCertificate", Name = "EuIntraCertificateNotFoundException", Namespace = "http://ec.europa.eu/tracesnt/certificate/euintra/v1")]
        [System.ServiceModel.FaultContractAttribute(typeof(TracesNT.WebServices.EuIntraCertificatePermissionDeniedExceptionType), Action = "getEuIntraSignedPdfCertificate", Name = "EuIntraCertificatePermissionDeniedException", Namespace = "http://ec.europa.eu/tracesnt/certificate/euintra/v1")]
        [System.ServiceModel.FaultContractAttribute(typeof(TracesNT.WebServices.EuIntraSignedPdfNotAvailableExceptionType), Action = "getEuIntraSignedPdfCertificate", Name = "EuIntraSignedPdfNotAvailableException", Namespace = "http://ec.europa.eu/tracesnt/certificate/euintra/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetEuIntraSignedPdfCertificateResponse> getEuIntraSignedPdfCertificateAsync(TracesNT.WebServices.GetEuIntraSignedPdfCertificateRequest request);
        [System.ServiceModel.OperationContractAttribute(Action = "findEuIntraCertificate", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action = "findEuIntraCertificate", Name = "IllegalFindCertificateException", Namespace = "http://ec.europa.eu/tracesnt/certificate/base/v01")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TracesNT.WebServices.FindEuIntraCertificateResponse> findEuIntraCertificateAsync(TracesNT.WebServices.FindEuIntraCertificateRequest request);
        [System.ServiceModel.OperationContractAttribute(Action = "getEuIntraCertificateStatus", ReplyAction = "*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string[]), Action = "getEuIntraCertificateStatus", Name = "EuIntraCertificatesNotFoundException", Namespace = "http://ec.europa.eu/tracesnt/certificate/euintra/v1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        System.Threading.Tasks.Task<TracesNT.WebServices.GetEuIntraCertificateStatusResponse> getEuIntraCertificateStatusAsync(TracesNT.WebServices.GetEuIntraCertificateStatusRequest request);
    }
}