//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DescriptorColumnNodeAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LegislationNodeAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassificationSectionNodeAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxonNodeAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SelectableDocumentLinkNodeAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MandatoryNotApplicableNodeAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(FieldAccessNodeAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AllowedNodeAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnumCollectionNodeAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EnumSingleNodeAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CardinalityNodeAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DoubleRangeNodeAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegerRangeNodeAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntegerNodeAttribute))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BooleanNodeAttribute))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/referencedata/nodeattribute/v1")]
    public abstract partial class AbstractNodeAttribute
    {
        private TextType descriptionField;
        private string mappedIdField;
        private string idField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public TextType Description
        {
            get
            {
                return this.descriptionField;
            }

            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string mappedId
        {
            get
            {
                return this.mappedIdField;
            }

            set
            {
                this.mappedIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string id
        {
            get
            {
                return this.idField;
            }

            set
            {
                this.idField = value;
            }
        }
    }
}