//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassificationTreeNodeDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassificationTreeNode))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/referencedata/classificationtree/v1")]
    public partial class AbstractClassificationTreeNode
    {
        private object itemField;
        private TextType descriptionField;
        private bool allowedForSelectionField;
        private ClassificationTreeNodeType typeField;
        private string pathField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CNCode", typeof(CodeType), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("CertificateModel", typeof(CertificateModelReference), Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute("Taxon", typeof(TaxonReference), Order = 0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }

            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public TextType Description
        {
            get
            {
                return this.descriptionField;
            }

            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool allowedForSelection
        {
            get
            {
                return this.allowedForSelectionField;
            }

            set
            {
                this.allowedForSelectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ClassificationTreeNodeType type
        {
            get
            {
                return this.typeField;
            }

            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string path
        {
            get
            {
                return this.pathField;
            }

            set
            {
                this.pathField = value;
            }
        }
    }
}