//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/referencedata/nodeattribute/v1")]
    public partial class CardinalityNodeAttribute : AbstractNodeAttribute
    {
        private CardinalityType cardinalityValueField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CardinalityType CardinalityValue
        {
            get
            {
                return this.cardinalityValueField;
            }

            set
            {
                this.cardinalityValueField = value;
            }
        }
    }
}