//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/referencedata/certificatemodel/v1")]
    public partial class CertificateModelReference
    {
        private TextType shortTitleField;
        private TextType longTitleField;
        private long modelIdField;
        private System.DateTime createdOnField;
        private System.DateTime updatedOnField;
        private bool updatedOnFieldSpecified;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public TextType ShortTitle
        {
            get
            {
                return this.shortTitleField;
            }

            set
            {
                this.shortTitleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public TextType LongTitle
        {
            get
            {
                return this.longTitleField;
            }

            set
            {
                this.longTitleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long modelId
        {
            get
            {
                return this.modelIdField;
            }

            set
            {
                this.modelIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime createdOn
        {
            get
            {
                return this.createdOnField;
            }

            set
            {
                this.createdOnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime updatedOn
        {
            get
            {
                return this.updatedOnField;
            }

            set
            {
                this.updatedOnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatedOnSpecified
        {
            get
            {
                return this.updatedOnFieldSpecified;
            }

            set
            {
                this.updatedOnFieldSpecified = value;
            }
        }
    }
}