//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/referencedata/certificatemodel/v1")]
    public enum CertificateModelInputType
    {
        /// <remarks/>
        RADIO_BUTTON,
        /// <remarks/>
        CHECKBOX,
        /// <remarks/>
        TEXTAREA,
        /// <remarks/>
        TEXT,
        /// <remarks/>
        EMAIL,
        /// <remarks/>
        URL,
        /// <remarks/>
        TIME,
        /// <remarks/>
        DATE,
        /// <remarks/>
        DATE_TIME,
        /// <remarks/>
        NUMBER,
    }
}