//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/ched/v06")]
    public partial class ChedQuantityManagementOutcomeType
    {
        private string quantityManagementOutcomeField;
        private string statusCodeField;
        private System.DateTime sendingDateField;
        private string operationCodeField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string QuantityManagementOutcome
        {
            get
            {
                return this.quantityManagementOutcomeField;
            }

            set
            {
                this.quantityManagementOutcomeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 1)]
        public string StatusCode
        {
            get
            {
                return this.statusCodeField;
            }

            set
            {
                this.statusCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public System.DateTime SendingDate
        {
            get
            {
                return this.sendingDateField;
            }

            set
            {
                this.sendingDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 3)]
        public string OperationCode
        {
            get
            {
                return this.operationCodeField;
            }

            set
            {
                this.operationCodeField = value;
            }
        }
    }
}