//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/certificate/ched/alert/noncompliance/v01")]
    public partial class ChedNonComplianceDetailsType
    {
        private StatusCodeType statusCodeField;
        private SPSAuthenticationType sPSAuthenticationField;
        private SPSReferencedDocumentType[] referenceSPSReferencedDocumentField;
        private SPSNoteType[] includedSPSNoteField;
        private ReasonsForRefusalType[] reasonsForRefusalField;
        private MeasureTakenType[] measureTakenField;
        private SPSPartyType placeOfInspectionSPSPartyField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public StatusCodeType StatusCode
        {
            get
            {
                return this.statusCodeField;
            }

            set
            {
                this.statusCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public SPSAuthenticationType SPSAuthentication
        {
            get
            {
                return this.sPSAuthenticationField;
            }

            set
            {
                this.sPSAuthenticationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceSPSReferencedDocument", Order = 2)]
        public SPSReferencedDocumentType[] ReferenceSPSReferencedDocument
        {
            get
            {
                return this.referenceSPSReferencedDocumentField;
            }

            set
            {
                this.referenceSPSReferencedDocumentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncludedSPSNote", Order = 3)]
        public SPSNoteType[] IncludedSPSNote
        {
            get
            {
                return this.includedSPSNoteField;
            }

            set
            {
                this.includedSPSNoteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReasonsForRefusal", Order = 4)]
        public ReasonsForRefusalType[] ReasonsForRefusal
        {
            get
            {
                return this.reasonsForRefusalField;
            }

            set
            {
                this.reasonsForRefusalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MeasureTaken", Order = 5)]
        public MeasureTakenType[] MeasureTaken
        {
            get
            {
                return this.measureTakenField;
            }

            set
            {
                this.measureTakenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public SPSPartyType PlaceOfInspectionSPSParty
        {
            get
            {
                return this.placeOfInspectionSPSPartyField;
            }

            set
            {
                this.placeOfInspectionSPSPartyField = value;
            }
        }
    }
}