//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/certificate/ched/followup/v01")]
    public partial class ChedFollowUpRedispatchDetailsType
    {
        private System.DateTime redispatchDateTimeField;
        private bool redispatchDateTimeFieldSpecified;
        private SPSPartyType exitAuthoritySPSPartyField;
        private SPSCountryType countryOfDestinationField;
        private ChedFollowUpMeansOfTransportType[] meansOfTransportField;
        private SPSPartyType placeOfDestinationSPSPartyField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public System.DateTime RedispatchDateTime
        {
            get
            {
                return this.redispatchDateTimeField;
            }

            set
            {
                this.redispatchDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RedispatchDateTimeSpecified
        {
            get
            {
                return this.redispatchDateTimeFieldSpecified;
            }

            set
            {
                this.redispatchDateTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public SPSPartyType ExitAuthoritySPSParty
        {
            get
            {
                return this.exitAuthoritySPSPartyField;
            }

            set
            {
                this.exitAuthoritySPSPartyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public SPSCountryType CountryOfDestination
        {
            get
            {
                return this.countryOfDestinationField;
            }

            set
            {
                this.countryOfDestinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MeansOfTransport", Order = 3)]
        public ChedFollowUpMeansOfTransportType[] MeansOfTransport
        {
            get
            {
                return this.meansOfTransportField;
            }

            set
            {
                this.meansOfTransportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public SPSPartyType PlaceOfDestinationSPSParty
        {
            get
            {
                return this.placeOfDestinationSPSPartyField;
            }

            set
            {
                this.placeOfDestinationSPSPartyField = value;
            }
        }
    }
}