//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/referencedata/nodeattribute/v1")]
    public partial class ClassificationSectionReference
    {
        private TextType descriptionField;
        private MetaCountryGroupReference[] scopeField;
        private OperatorActivityTypeReference[] operatorActivityTypeField;
        private string codeField;
        private string chapterField;
        private bool lmsField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public TextType Description
        {
            get
            {
                return this.descriptionField;
            }

            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Scope", Order = 1)]
        public MetaCountryGroupReference[] Scope
        {
            get
            {
                return this.scopeField;
            }

            set
            {
                this.scopeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OperatorActivityType", Order = 2)]
        public OperatorActivityTypeReference[] OperatorActivityType
        {
            get
            {
                return this.operatorActivityTypeField;
            }

            set
            {
                this.operatorActivityTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string code
        {
            get
            {
                return this.codeField;
            }

            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string chapter
        {
            get
            {
                return this.chapterField;
            }

            set
            {
                this.chapterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool lms
        {
            get
            {
                return this.lmsField;
            }

            set
            {
                this.lmsField = value;
            }
        }
    }
}