//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/referencedata/classificationtree/v1")]
    public partial class ClassificationTreeNode : AbstractClassificationTreeNode
    {
        private ClassificationTreeNode[] nodeField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Node", Order = 0)]
        public ClassificationTreeNode[] Node
        {
            get
            {
                return this.nodeField;
            }

            set
            {
                this.nodeField = value;
            }
        }
    }
}