//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/certificate/ched/alert/noncompliance/v01")]
    public partial class ConcernedSPSConsignmentItemType
    {
        private CargoTypeClassificationCodeType typeCodeField;
        private ConcernedSPSTradeLineItemType[] concernedSPSTradeLineItemField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CargoTypeClassificationCodeType TypeCode
        {
            get
            {
                return this.typeCodeField;
            }

            set
            {
                this.typeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConcernedSPSTradeLineItem", Order = 1)]
        public ConcernedSPSTradeLineItemType[] ConcernedSPSTradeLineItem
        {
            get
            {
                return this.concernedSPSTradeLineItemField;
            }

            set
            {
                this.concernedSPSTradeLineItemField = value;
            }
        }
    }
}