//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/base/v03")]
    public partial class DateTimeRangeWithNumericalFreqType
    {
        private System.DateTime dateTimeFromField;
        private bool dateTimeFromFieldSpecified;
        private System.DateTime dateTimeToField;
        private bool dateTimeToFieldSpecified;
        private string subscriptionFrequencyField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public System.DateTime DateTimeFrom
        {
            get
            {
                return this.dateTimeFromField;
            }

            set
            {
                this.dateTimeFromField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateTimeFromSpecified
        {
            get
            {
                return this.dateTimeFromFieldSpecified;
            }

            set
            {
                this.dateTimeFromFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public System.DateTime DateTimeTo
        {
            get
            {
                return this.dateTimeToField;
            }

            set
            {
                this.dateTimeToField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateTimeToSpecified
        {
            get
            {
                return this.dateTimeToFieldSpecified;
            }

            set
            {
                this.dateTimeToFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 2)]
        public string SubscriptionFrequency
        {
            get
            {
                return this.subscriptionFrequencyField;
            }

            set
            {
                this.subscriptionFrequencyField = value;
            }
        }
    }
}