//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/referencedata/nodeattribute/v1")]
    public enum DescriptorColumnType
    {
        /// <remarks/>
        QUANTITY,
        /// <remarks/>
        BOOLEAN,
        /// <remarks/>
        STRING,
        /// <remarks/>
        DATETIME,
        /// <remarks/>
        PARTIAL_TIME,
        /// <remarks/>
        ENUMERATION,
        /// <remarks/>
        COUNTRY_CODE,
        /// <remarks/>
        REGION,
        /// <remarks/>
        SANITARY_REGION,
        /// <remarks/>
        TAXON,
        /// <remarks/>
        TAXON_INVASIVE,
        /// <remarks/>
        MEANS_OF_TRANSPORT_SHIP,
        /// <remarks/>
        OPERATOR_ACTIVITY,
        /// <remarks/>
        ORGANIC_CONTROL_BODY_ACTIVITY,
        /// <remarks/>
        CATCH_AREA,
        /// <remarks/>
        DESCRIPTOR_ROW,
        /// <remarks/>
        CLASSIFICATION_NODE_REFERENCE,
        /// <remarks/>
        DYNAMIC,
    }
}