//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/certificate/docom/retrieval/v1")]
    public partial class DocomCertificateQueryResultType
    {
        private string idField;
        private StatusCodeType statusField;
        private bool hasFollowUpsField;
        private bool hasFollowUpsFieldSpecified;
        private string localIDField;
        private SPSClassificationType[] commodityApplicableSPSClassificationField;
        private System.DateTime createDateTimeField;
        private System.DateTime updateDateTimeField;
        private System.DateTime statusChangeDateTimeField;
        private bool statusChangeDateTimeFieldSpecified;
        private System.DateTime declarationDateTimeField;
        private bool declarationDateTimeFieldSpecified;
        private string centralCompetentAuthorityCodeField;
        private string centralCompetentAuthorityUnLocodeField;
        private string localCompetentAuthorityCodeField;
        private string localCompetentAuthorityUnLocodeField;
        private IDType countryOfConsignorField;
        private IDType countryOfConsigneeField;
        private IDType countryOfDealerField;
        private IDType[] countryOfOriginField;
        private IDType countryOfDestinationField;
        private IDType countryOfPlaceOfLoadingField;
        private IDType[] countryOfTransitField;
        private IDType countryOfDestinationForExportField;
        private string consignorNameField;
        private string consigneeNameField;
        private SPSReferencedDocumentType[] referenceSPSReferencedDocumentField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token", Order = 0)]
        public string ID
        {
            get
            {
                return this.idField;
            }

            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public StatusCodeType Status
        {
            get
            {
                return this.statusField;
            }

            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public bool HasFollowUps
        {
            get
            {
                return this.hasFollowUpsField;
            }

            set
            {
                this.hasFollowUpsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool HasFollowUpsSpecified
        {
            get
            {
                return this.hasFollowUpsFieldSpecified;
            }

            set
            {
                this.hasFollowUpsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token", Order = 3)]
        public string LocalID
        {
            get
            {
                return this.localIDField;
            }

            set
            {
                this.localIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CommodityApplicableSPSClassification", Order = 4)]
        public SPSClassificationType[] CommodityApplicableSPSClassification
        {
            get
            {
                return this.commodityApplicableSPSClassificationField;
            }

            set
            {
                this.commodityApplicableSPSClassificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public System.DateTime CreateDateTime
        {
            get
            {
                return this.createDateTimeField;
            }

            set
            {
                this.createDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public System.DateTime UpdateDateTime
        {
            get
            {
                return this.updateDateTimeField;
            }

            set
            {
                this.updateDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public System.DateTime StatusChangeDateTime
        {
            get
            {
                return this.statusChangeDateTimeField;
            }

            set
            {
                this.statusChangeDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusChangeDateTimeSpecified
        {
            get
            {
                return this.statusChangeDateTimeFieldSpecified;
            }

            set
            {
                this.statusChangeDateTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public System.DateTime DeclarationDateTime
        {
            get
            {
                return this.declarationDateTimeField;
            }

            set
            {
                this.declarationDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeclarationDateTimeSpecified
        {
            get
            {
                return this.declarationDateTimeFieldSpecified;
            }

            set
            {
                this.declarationDateTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token", Order = 9)]
        public string CentralCompetentAuthorityCode
        {
            get
            {
                return this.centralCompetentAuthorityCodeField;
            }

            set
            {
                this.centralCompetentAuthorityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token", Order = 10)]
        public string CentralCompetentAuthorityUnLocode
        {
            get
            {
                return this.centralCompetentAuthorityUnLocodeField;
            }

            set
            {
                this.centralCompetentAuthorityUnLocodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token", Order = 11)]
        public string LocalCompetentAuthorityCode
        {
            get
            {
                return this.localCompetentAuthorityCodeField;
            }

            set
            {
                this.localCompetentAuthorityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "token", Order = 12)]
        public string LocalCompetentAuthorityUnLocode
        {
            get
            {
                return this.localCompetentAuthorityUnLocodeField;
            }

            set
            {
                this.localCompetentAuthorityUnLocodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 13)]
        public IDType CountryOfConsignor
        {
            get
            {
                return this.countryOfConsignorField;
            }

            set
            {
                this.countryOfConsignorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 14)]
        public IDType CountryOfConsignee
        {
            get
            {
                return this.countryOfConsigneeField;
            }

            set
            {
                this.countryOfConsigneeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 15)]
        public IDType CountryOfDealer
        {
            get
            {
                return this.countryOfDealerField;
            }

            set
            {
                this.countryOfDealerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CountryOfOrigin", Order = 16)]
        public IDType[] CountryOfOrigin
        {
            get
            {
                return this.countryOfOriginField;
            }

            set
            {
                this.countryOfOriginField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 17)]
        public IDType CountryOfDestination
        {
            get
            {
                return this.countryOfDestinationField;
            }

            set
            {
                this.countryOfDestinationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 18)]
        public IDType CountryOfPlaceOfLoading
        {
            get
            {
                return this.countryOfPlaceOfLoadingField;
            }

            set
            {
                this.countryOfPlaceOfLoadingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CountryOfTransit", Order = 19)]
        public IDType[] CountryOfTransit
        {
            get
            {
                return this.countryOfTransitField;
            }

            set
            {
                this.countryOfTransitField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 20)]
        public IDType CountryOfDestinationForExport
        {
            get
            {
                return this.countryOfDestinationForExportField;
            }

            set
            {
                this.countryOfDestinationForExportField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 21)]
        public string ConsignorName
        {
            get
            {
                return this.consignorNameField;
            }

            set
            {
                this.consignorNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 22)]
        public string ConsigneeName
        {
            get
            {
                return this.consigneeNameField;
            }

            set
            {
                this.consigneeNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ReferenceSPSReferencedDocument", Order = 23)]
        public SPSReferencedDocumentType[] ReferenceSPSReferencedDocument
        {
            get
            {
                return this.referenceSPSReferencedDocumentField;
            }

            set
            {
                this.referenceSPSReferencedDocumentField = value;
            }
        }
    }
}