//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/certificate/docom/retrieval/v1")]
    public partial class DocomCertificateType
    {
        private SPSCertificateType sPSCertificateField;
        private DocomFollowUpType[] docomFollowUpField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public SPSCertificateType SPSCertificate
        {
            get
            {
                return this.sPSCertificateField;
            }

            set
            {
                this.sPSCertificateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocomFollowUp", Order = 1)]
        public DocomFollowUpType[] DocomFollowUp
        {
            get
            {
                return this.docomFollowUpField;
            }

            set
            {
                this.docomFollowUpField = value;
            }
        }
    }
}