//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/referencedata/nodeattribute/v1")]
    public enum FieldAccessNodeAttributeValue
    {
        /// <remarks/>
        MANDATORY,
        /// <remarks/>
        OPTIONAL,
        /// <remarks/>
        DISABLED,
        /// <remarks/>
        NOT_AVAILABLE,
    }
}