//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/certificate/euintra/v1")]
    public partial class FindEuIntraCertificateResultType
    {
        private EuIntraCertificateQueryResultType[] euIntraCertificateResultField;
        private int pageSizeField;
        private int offsetField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EuIntraCertificateResult", Order = 0)]
        public EuIntraCertificateQueryResultType[] EuIntraCertificateResult
        {
            get
            {
                return this.euIntraCertificateResultField;
            }

            set
            {
                this.euIntraCertificateResultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int pageSize
        {
            get
            {
                return this.pageSizeField;
            }

            set
            {
                this.pageSizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int offset
        {
            get
            {
                return this.offsetField;
            }

            set
            {
                this.offsetField = value;
            }
        }
    }
}