//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:un:unece:uncefact:codelist:standard:ISO:ISO2AlphaLanguageCode:2006-10-27")]
    public enum ISO2AlphaLanguageCodeContentType
    {
        /// <remarks/>
        aa,
        /// <remarks/>
        AA,
        /// <remarks/>
        ab,
        /// <remarks/>
        AB,
        /// <remarks/>
        ae,
        /// <remarks/>
        AE,
        /// <remarks/>
        af,
        /// <remarks/>
        AF,
        /// <remarks/>
        ak,
        /// <remarks/>
        AK,
        /// <remarks/>
        am,
        /// <remarks/>
        AM,
        /// <remarks/>
        an,
        /// <remarks/>
        AN,
        /// <remarks/>
        ar,
        /// <remarks/>
        AR,
        /// <remarks/>
        @as,
        /// <remarks/>
        AS,
        /// <remarks/>
        av,
        /// <remarks/>
        AV,
        /// <remarks/>
        ay,
        /// <remarks/>
        AY,
        /// <remarks/>
        az,
        /// <remarks/>
        AZ,
        /// <remarks/>
        ba,
        /// <remarks/>
        BA,
        /// <remarks/>
        be,
        /// <remarks/>
        BE,
        /// <remarks/>
        bg,
        /// <remarks/>
        BG,
        /// <remarks/>
        bh,
        /// <remarks/>
        BH,
        /// <remarks/>
        bi,
        /// <remarks/>
        BI,
        /// <remarks/>
        bm,
        /// <remarks/>
        BM,
        /// <remarks/>
        bn,
        /// <remarks/>
        BN,
        /// <remarks/>
        bo,
        /// <remarks/>
        BO,
        /// <remarks/>
        br,
        /// <remarks/>
        BR,
        /// <remarks/>
        bs,
        /// <remarks/>
        BS,
        /// <remarks/>
        ca,
        /// <remarks/>
        CA,
        /// <remarks/>
        ce,
        /// <remarks/>
        CE,
        /// <remarks/>
        ch,
        /// <remarks/>
        CH,
        /// <remarks/>
        co,
        /// <remarks/>
        CO,
        /// <remarks/>
        cr,
        /// <remarks/>
        CR,
        /// <remarks/>
        cs,
        /// <remarks/>
        CS,
        /// <remarks/>
        cu,
        /// <remarks/>
        CU,
        /// <remarks/>
        cv,
        /// <remarks/>
        CV,
        /// <remarks/>
        cy,
        /// <remarks/>
        CY,
        /// <remarks/>
        da,
        /// <remarks/>
        DA,
        /// <remarks/>
        de,
        /// <remarks/>
        DE,
        /// <remarks/>
        dv,
        /// <remarks/>
        DV,
        /// <remarks/>
        dz,
        /// <remarks/>
        DZ,
        /// <remarks/>
        ee,
        /// <remarks/>
        EE,
        /// <remarks/>
        el,
        /// <remarks/>
        EL,
        /// <remarks/>
        en,
        /// <remarks/>
        EN,
        /// <remarks/>
        eo,
        /// <remarks/>
        EO,
        /// <remarks/>
        es,
        /// <remarks/>
        ES,
        /// <remarks/>
        et,
        /// <remarks/>
        ET,
        /// <remarks/>
        eu,
        /// <remarks/>
        EU,
        /// <remarks/>
        fa,
        /// <remarks/>
        FA,
        /// <remarks/>
        ff,
        /// <remarks/>
        FF,
        /// <remarks/>
        fi,
        /// <remarks/>
        FI,
        /// <remarks/>
        fj,
        /// <remarks/>
        FJ,
        /// <remarks/>
        fo,
        /// <remarks/>
        FO,
        /// <remarks/>
        fr,
        /// <remarks/>
        FR,
        /// <remarks/>
        fy,
        /// <remarks/>
        FY,
        /// <remarks/>
        ga,
        /// <remarks/>
        GA,
        /// <remarks/>
        gd,
        /// <remarks/>
        GD,
        /// <remarks/>
        gl,
        /// <remarks/>
        GL,
        /// <remarks/>
        gn,
        /// <remarks/>
        GN,
        /// <remarks/>
        gu,
        /// <remarks/>
        GU,
        /// <remarks/>
        gv,
        /// <remarks/>
        GV,
        /// <remarks/>
        ha,
        /// <remarks/>
        HA,
        /// <remarks/>
        he,
        /// <remarks/>
        HE,
        /// <remarks/>
        hi,
        /// <remarks/>
        HI,
        /// <remarks/>
        ho,
        /// <remarks/>
        HO,
        /// <remarks/>
        hr,
        /// <remarks/>
        HR,
        /// <remarks/>
        ht,
        /// <remarks/>
        HT,
        /// <remarks/>
        hu,
        /// <remarks/>
        HU,
        /// <remarks/>
        hy,
        /// <remarks/>
        HY,
        /// <remarks/>
        hz,
        /// <remarks/>
        HZ,
        /// <remarks/>
        ia,
        /// <remarks/>
        IA,
        /// <remarks/>
        id,
        /// <remarks/>
        ID,
        /// <remarks/>
        ie,
        /// <remarks/>
        IE,
        /// <remarks/>
        ig,
        /// <remarks/>
        IG,
        /// <remarks/>
        ii,
        /// <remarks/>
        II,
        /// <remarks/>
        ik,
        /// <remarks/>
        IK,
        /// <remarks/>
        io,
        /// <remarks/>
        IO,
        /// <remarks/>
        @is,
        /// <remarks/>
        IS,
        /// <remarks/>
        it,
        /// <remarks/>
        IT,
        /// <remarks/>
        iu,
        /// <remarks/>
        IU,
        /// <remarks/>
        ja,
        /// <remarks/>
        JA,
        /// <remarks/>
        jv,
        /// <remarks/>
        JV,
        /// <remarks/>
        ka,
        /// <remarks/>
        KA,
        /// <remarks/>
        kg,
        /// <remarks/>
        KG,
        /// <remarks/>
        ki,
        /// <remarks/>
        KI,
        /// <remarks/>
        kj,
        /// <remarks/>
        KJ,
        /// <remarks/>
        kk,
        /// <remarks/>
        KK,
        /// <remarks/>
        kl,
        /// <remarks/>
        KL,
        /// <remarks/>
        km,
        /// <remarks/>
        KM,
        /// <remarks/>
        kn,
        /// <remarks/>
        KN,
        /// <remarks/>
        ko,
        /// <remarks/>
        KO,
        /// <remarks/>
        kr,
        /// <remarks/>
        KR,
        /// <remarks/>
        ks,
        /// <remarks/>
        KS,
        /// <remarks/>
        ku,
        /// <remarks/>
        KU,
        /// <remarks/>
        kv,
        /// <remarks/>
        KV,
        /// <remarks/>
        kw,
        /// <remarks/>
        KW,
        /// <remarks/>
        ky,
        /// <remarks/>
        KY,
        /// <remarks/>
        la,
        /// <remarks/>
        LA,
        /// <remarks/>
        lb,
        /// <remarks/>
        LB,
        /// <remarks/>
        lg,
        /// <remarks/>
        LG,
        /// <remarks/>
        li,
        /// <remarks/>
        LI,
        /// <remarks/>
        ln,
        /// <remarks/>
        LN,
        /// <remarks/>
        lo,
        /// <remarks/>
        LO,
        /// <remarks/>
        lt,
        /// <remarks/>
        LT,
        /// <remarks/>
        lu,
        /// <remarks/>
        LU,
        /// <remarks/>
        lv,
        /// <remarks/>
        LV,
        /// <remarks/>
        mg,
        /// <remarks/>
        MG,
        /// <remarks/>
        mh,
        /// <remarks/>
        MH,
        /// <remarks/>
        mi,
        /// <remarks/>
        MI,
        /// <remarks/>
        mk,
        /// <remarks/>
        MK,
        /// <remarks/>
        ml,
        /// <remarks/>
        ML,
        /// <remarks/>
        mn,
        /// <remarks/>
        MN,
        /// <remarks/>
        mo,
        /// <remarks/>
        MO,
        /// <remarks/>
        mr,
        /// <remarks/>
        MR,
        /// <remarks/>
        ms,
        /// <remarks/>
        MS,
        /// <remarks/>
        mt,
        /// <remarks/>
        MT,
        /// <remarks/>
        my,
        /// <remarks/>
        MY,
        /// <remarks/>
        na,
        /// <remarks/>
        NA,
        /// <remarks/>
        nb,
        /// <remarks/>
        NB,
        /// <remarks/>
        nd,
        /// <remarks/>
        ND,
        /// <remarks/>
        ne,
        /// <remarks/>
        NE,
        /// <remarks/>
        ng,
        /// <remarks/>
        NG,
        /// <remarks/>
        nl,
        /// <remarks/>
        NL,
        /// <remarks/>
        nn,
        /// <remarks/>
        NN,
        /// <remarks/>
        no,
        /// <remarks/>
        NO,
        /// <remarks/>
        nr,
        /// <remarks/>
        NR,
        /// <remarks/>
        nv,
        /// <remarks/>
        NV,
        /// <remarks/>
        ny,
        /// <remarks/>
        NY,
        /// <remarks/>
        oc,
        /// <remarks/>
        OC,
        /// <remarks/>
        oj,
        /// <remarks/>
        OJ,
        /// <remarks/>
        om,
        /// <remarks/>
        OM,
        /// <remarks/>
        or,
        /// <remarks/>
        OR,
        /// <remarks/>
        os,
        /// <remarks/>
        OS,
        /// <remarks/>
        pa,
        /// <remarks/>
        PA,
        /// <remarks/>
        pi,
        /// <remarks/>
        PI,
        /// <remarks/>
        pl,
        /// <remarks/>
        PL,
        /// <remarks/>
        ps,
        /// <remarks/>
        PS,
        /// <remarks/>
        pt,
        /// <remarks/>
        PT,
        /// <remarks/>
        qu,
        /// <remarks/>
        QU,
        /// <remarks/>
        rm,
        /// <remarks/>
        RM,
        /// <remarks/>
        rn,
        /// <remarks/>
        RN,
        /// <remarks/>
        ro,
        /// <remarks/>
        RO,
        /// <remarks/>
        ru,
        /// <remarks/>
        RU,
        /// <remarks/>
        rw,
        /// <remarks/>
        RW,
        /// <remarks/>
        sa,
        /// <remarks/>
        SA,
        /// <remarks/>
        sc,
        /// <remarks/>
        SC,
        /// <remarks/>
        sd,
        /// <remarks/>
        SD,
        /// <remarks/>
        se,
        /// <remarks/>
        SE,
        /// <remarks/>
        sg,
        /// <remarks/>
        SG,
        /// <remarks/>
        si,
        /// <remarks/>
        SI,
        /// <remarks/>
        sk,
        /// <remarks/>
        SK,
        /// <remarks/>
        sl,
        /// <remarks/>
        SL,
        /// <remarks/>
        sm,
        /// <remarks/>
        SM,
        /// <remarks/>
        sn,
        /// <remarks/>
        SN,
        /// <remarks/>
        so,
        /// <remarks/>
        SO,
        /// <remarks/>
        sq,
        /// <remarks/>
        SQ,
        /// <remarks/>
        sr,
        /// <remarks/>
        SR,
        /// <remarks/>
        ss,
        /// <remarks/>
        SS,
        /// <remarks/>
        st,
        /// <remarks/>
        ST,
        /// <remarks/>
        su,
        /// <remarks/>
        SU,
        /// <remarks/>
        sv,
        /// <remarks/>
        SV,
        /// <remarks/>
        sw,
        /// <remarks/>
        SW,
        /// <remarks/>
        ta,
        /// <remarks/>
        TA,
        /// <remarks/>
        te,
        /// <remarks/>
        TE,
        /// <remarks/>
        tg,
        /// <remarks/>
        TG,
        /// <remarks/>
        th,
        /// <remarks/>
        TH,
        /// <remarks/>
        ti,
        /// <remarks/>
        TI,
        /// <remarks/>
        tk,
        /// <remarks/>
        TK,
        /// <remarks/>
        tl,
        /// <remarks/>
        TL,
        /// <remarks/>
        tn,
        /// <remarks/>
        TN,
        /// <remarks/>
        to,
        /// <remarks/>
        TO,
        /// <remarks/>
        tr,
        /// <remarks/>
        TR,
        /// <remarks/>
        ts,
        /// <remarks/>
        TS,
        /// <remarks/>
        tt,
        /// <remarks/>
        TT,
        /// <remarks/>
        tw,
        /// <remarks/>
        TW,
        /// <remarks/>
        ty,
        /// <remarks/>
        TY,
        /// <remarks/>
        ug,
        /// <remarks/>
        UG,
        /// <remarks/>
        uk,
        /// <remarks/>
        UK,
        /// <remarks/>
        ur,
        /// <remarks/>
        UR,
        /// <remarks/>
        uz,
        /// <remarks/>
        UZ,
        /// <remarks/>
        ve,
        /// <remarks/>
        VE,
        /// <remarks/>
        vi,
        /// <remarks/>
        VI,
        /// <remarks/>
        vo,
        /// <remarks/>
        VO,
        /// <remarks/>
        wa,
        /// <remarks/>
        WA,
        /// <remarks/>
        wo,
        /// <remarks/>
        WO,
        /// <remarks/>
        xh,
        /// <remarks/>
        XH,
        /// <remarks/>
        yi,
        /// <remarks/>
        YI,
        /// <remarks/>
        yo,
        /// <remarks/>
        YO,
        /// <remarks/>
        za,
        /// <remarks/>
        ZA,
        /// <remarks/>
        zh,
        /// <remarks/>
        ZH,
        /// <remarks/>
        zu,
        /// <remarks/>
        ZU,
    }
}