//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/referencedata/nodeattribute/v1")]
    public partial class LegislationReference
    {
        private IDType[] celexIdentifierField;
        private CertificateModelReference[] certificateModelField;
        private IDType[] originCountryField;
        private IDType[] destinationCountryField;
        private ClassificationSectionReference[] originClassificationSectionField;
        private ClassificationSectionReference[] destinationClassificationSectionField;
        private long legislationIdField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CelexIdentifier", Order = 0)]
        public IDType[] CelexIdentifier
        {
            get
            {
                return this.celexIdentifierField;
            }

            set
            {
                this.celexIdentifierField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CertificateModel", Order = 1)]
        public CertificateModelReference[] CertificateModel
        {
            get
            {
                return this.certificateModelField;
            }

            set
            {
                this.certificateModelField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OriginCountry", Order = 2)]
        public IDType[] OriginCountry
        {
            get
            {
                return this.originCountryField;
            }

            set
            {
                this.originCountryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DestinationCountry", Order = 3)]
        public IDType[] DestinationCountry
        {
            get
            {
                return this.destinationCountryField;
            }

            set
            {
                this.destinationCountryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OriginClassificationSection", Order = 4)]
        public ClassificationSectionReference[] OriginClassificationSection
        {
            get
            {
                return this.originClassificationSectionField;
            }

            set
            {
                this.originClassificationSectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DestinationClassificationSection", Order = 5)]
        public ClassificationSectionReference[] DestinationClassificationSection
        {
            get
            {
                return this.destinationClassificationSectionField;
            }

            set
            {
                this.destinationClassificationSectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long legislationId
        {
            get
            {
                return this.legislationIdField;
            }

            set
            {
                this.legislationIdField = value;
            }
        }
    }
}