//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:un:unece:uncefact:codelist:standard:UNECE:LocationFunctionCode:D16B")]
    public enum LocationFunctionCodeContentType
    {
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("5")]
        Item5,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6")]
        Item6,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("7")]
        Item7,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8")]
        Item8,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("9")]
        Item9,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("18")]
        Item18,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("19")]
        Item19,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("21")]
        Item21,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("22")]
        Item22,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("23")]
        Item23,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("24")]
        Item24,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25")]
        Item25,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("26")]
        Item26,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("27")]
        Item27,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("28")]
        Item28,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("29")]
        Item29,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("30")]
        Item30,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("31")]
        Item31,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32")]
        Item32,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("33")]
        Item33,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("34")]
        Item34,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("35")]
        Item35,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("36")]
        Item36,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("37")]
        Item37,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("38")]
        Item38,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("39")]
        Item39,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("41")]
        Item41,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43")]
        Item43,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44")]
        Item44,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("45")]
        Item45,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("46")]
        Item46,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("47")]
        Item47,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("48")]
        Item48,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("49")]
        Item49,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("50")]
        Item50,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("51")]
        Item51,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("52")]
        Item52,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("53")]
        Item53,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("54")]
        Item54,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("55")]
        Item55,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("56")]
        Item56,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("57")]
        Item57,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("58")]
        Item58,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("59")]
        Item59,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("60")]
        Item60,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("61")]
        Item61,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("62")]
        Item62,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("63")]
        Item63,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("64")]
        Item64,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("65")]
        Item65,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("66")]
        Item66,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("67")]
        Item67,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("68")]
        Item68,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("69")]
        Item69,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("70")]
        Item70,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("71")]
        Item71,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("72")]
        Item72,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("73")]
        Item73,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("74")]
        Item74,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("75")]
        Item75,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("76")]
        Item76,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("77")]
        Item77,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("78")]
        Item78,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("79")]
        Item79,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("80")]
        Item80,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("81")]
        Item81,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("82")]
        Item82,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("83")]
        Item83,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("84")]
        Item84,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("85")]
        Item85,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("86")]
        Item86,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("87")]
        Item87,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("88")]
        Item88,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("89")]
        Item89,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("90")]
        Item90,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("91")]
        Item91,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("92")]
        Item92,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("93")]
        Item93,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("94")]
        Item94,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("95")]
        Item95,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("96")]
        Item96,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("97")]
        Item97,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("98")]
        Item98,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("100")]
        Item100,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("101")]
        Item101,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("103")]
        Item103,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("104")]
        Item104,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("105")]
        Item105,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("106")]
        Item106,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("107")]
        Item107,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("108")]
        Item108,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("109")]
        Item109,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("110")]
        Item110,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("111")]
        Item111,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("112")]
        Item112,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("113")]
        Item113,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("114")]
        Item114,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("115")]
        Item115,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("116")]
        Item116,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("117")]
        Item117,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("118")]
        Item118,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("119")]
        Item119,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("120")]
        Item120,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("122")]
        Item122,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("123")]
        Item123,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("124")]
        Item124,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("125")]
        Item125,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("126")]
        Item126,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("127")]
        Item127,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("128")]
        Item128,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("129")]
        Item129,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("130")]
        Item130,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("131")]
        Item131,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("132")]
        Item132,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("133")]
        Item133,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("134")]
        Item134,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("135")]
        Item135,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("136")]
        Item136,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("137")]
        Item137,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("138")]
        Item138,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("139")]
        Item139,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("140")]
        Item140,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("141")]
        Item141,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("142")]
        Item142,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("143")]
        Item143,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("144")]
        Item144,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("145")]
        Item145,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("146")]
        Item146,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("147")]
        Item147,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("148")]
        Item148,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("149")]
        Item149,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("150")]
        Item150,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("151")]
        Item151,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("152")]
        Item152,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("153")]
        Item153,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("154")]
        Item154,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("155")]
        Item155,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("156")]
        Item156,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("157")]
        Item157,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("158")]
        Item158,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("159")]
        Item159,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("160")]
        Item160,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("161")]
        Item161,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("162")]
        Item162,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("163")]
        Item163,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("164")]
        Item164,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("165")]
        Item165,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("166")]
        Item166,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("167")]
        Item167,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("168")]
        Item168,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("169")]
        Item169,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("170")]
        Item170,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("171")]
        Item171,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("172")]
        Item172,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("173")]
        Item173,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("174")]
        Item174,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("175")]
        Item175,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("176")]
        Item176,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("177")]
        Item177,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("178")]
        Item178,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("179")]
        Item179,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("180")]
        Item180,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("181")]
        Item181,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("182")]
        Item182,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("183")]
        Item183,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("184")]
        Item184,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("185")]
        Item185,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("186")]
        Item186,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("187")]
        Item187,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("188")]
        Item188,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("189")]
        Item189,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("190")]
        Item190,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("191")]
        Item191,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("192")]
        Item192,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("193")]
        Item193,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("194")]
        Item194,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("195")]
        Item195,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("196")]
        Item196,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("197")]
        Item197,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("198")]
        Item198,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("199")]
        Item199,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("200")]
        Item200,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("201")]
        Item201,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("202")]
        Item202,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("203")]
        Item203,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("204")]
        Item204,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("205")]
        Item205,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("206")]
        Item206,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("207")]
        Item207,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("208")]
        Item208,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("209")]
        Item209,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("210")]
        Item210,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("211")]
        Item211,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("212")]
        Item212,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("213")]
        Item213,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("214")]
        Item214,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("215")]
        Item215,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("216")]
        Item216,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("217")]
        Item217,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("218")]
        Item218,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("219")]
        Item219,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("220")]
        Item220,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("221")]
        Item221,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("222")]
        Item222,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("223")]
        Item223,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("224")]
        Item224,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("225")]
        Item225,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("226")]
        Item226,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("227")]
        Item227,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("228")]
        Item228,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("229")]
        Item229,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("230")]
        Item230,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("231")]
        Item231,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("232")]
        Item232,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("233")]
        Item233,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("234")]
        Item234,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("235")]
        Item235,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("236")]
        Item236,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("237")]
        Item237,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("238")]
        Item238,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("239")]
        Item239,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("240")]
        Item240,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("241")]
        Item241,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("242")]
        Item242,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("243")]
        Item243,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("244")]
        Item244,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("245")]
        Item245,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("246")]
        Item246,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("247")]
        Item247,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("248")]
        Item248,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("249")]
        Item249,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("250")]
        Item250,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("251")]
        Item251,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("252")]
        Item252,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("253")]
        Item253,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("254")]
        Item254,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("255")]
        Item255,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("256")]
        Item256,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("257")]
        Item257,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("258")]
        Item258,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("259")]
        Item259,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("260")]
        Item260,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("261")]
        Item261,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("262")]
        Item262,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("263")]
        Item263,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("264")]
        Item264,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("265")]
        Item265,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("266")]
        Item266,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("267")]
        Item267,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("268")]
        Item268,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("269")]
        Item269,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("270")]
        Item270,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("271")]
        Item271,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("272")]
        Item272,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("273")]
        Item273,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("274")]
        Item274,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("275")]
        Item275,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("276")]
        Item276,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("277")]
        Item277,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("278")]
        Item278,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("279")]
        Item279,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("280")]
        Item280,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("281")]
        Item281,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("282")]
        Item282,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("283")]
        Item283,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("284")]
        Item284,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("285")]
        Item285,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("286")]
        Item286,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("287")]
        Item287,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("288")]
        Item288,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("289")]
        Item289,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("290")]
        Item290,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("291")]
        Item291,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("292")]
        Item292,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("293")]
        Item293,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("294")]
        Item294,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("295")]
        Item295,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("296")]
        Item296,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("297")]
        Item297,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("298")]
        Item298,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("299")]
        Item299,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("300")]
        Item300,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("301")]
        Item301,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("302")]
        Item302,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("303")]
        Item303,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("304")]
        Item304,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("305")]
        Item305,
        /// <remarks/>
        ZZZ,
    }
}