//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/base/v03")]
    public enum MassQuantityTypeUnitCode
    {
        /// <remarks/>
        TNE,
        /// <remarks/>
        KTN,
        /// <remarks/>
        KGM,
        /// <remarks/>
        GRM,
    }
}