//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/base/v03")]
    public partial class PrevalidationFailureConsignmentItemType
    {
        private string goodsItemNumberField;
        private string documentLineItemNumberField;
        private string reasonForPrevalidationFailureField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 0)]
        public string GoodsItemNumber
        {
            get
            {
                return this.goodsItemNumberField;
            }

            set
            {
                this.goodsItemNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer", Order = 1)]
        public string DocumentLineItemNumber
        {
            get
            {
                return this.documentLineItemNumberField;
            }

            set
            {
                this.documentLineItemNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string ReasonForPrevalidationFailure
        {
            get
            {
                return this.reasonForPrevalidationFailureField;
            }

            set
            {
                this.reasonForPrevalidationFailureField = value;
            }
        }
    }
}