//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/base/v03")]
    public partial class ProductQuantityEnhancedPlusPlusType
    {
        private CommodityCodeEnhanced4AvailableType commodityCodeField;
        private SWSupportingDocumentType swSupportingDocumentField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CommodityCodeEnhanced4AvailableType CommodityCode
        {
            get
            {
                return this.commodityCodeField;
            }

            set
            {
                this.commodityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public SWSupportingDocumentType SwSupportingDocument
        {
            get
            {
                return this.swSupportingDocumentField;
            }

            set
            {
                this.swSupportingDocumentField = value;
            }
        }
    }
}