//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/base/v03")]
    public partial class QuantitiesPrevalidationResultEnhancedType
    {
        private bool expectedPrevalReservationResultField;
        private string[] expectedPrevalReservationFailureReasonField;
        private PrevalidationFailureConsignmentItemType[] prevalidationFailureConsignmentItemField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public bool ExpectedPrevalReservationResult
        {
            get
            {
                return this.expectedPrevalReservationResultField;
            }

            set
            {
                this.expectedPrevalReservationResultField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExpectedPrevalReservationFailureReason", Order = 1)]
        public string[] ExpectedPrevalReservationFailureReason
        {
            get
            {
                return this.expectedPrevalReservationFailureReasonField;
            }

            set
            {
                this.expectedPrevalReservationFailureReasonField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PrevalidationFailureConsignmentItem", Order = 2)]
        public PrevalidationFailureConsignmentItemType[] PrevalidationFailureConsignmentItem
        {
            get
            {
                return this.prevalidationFailureConsignmentItemField;
            }

            set
            {
                this.prevalidationFailureConsignmentItemField = value;
            }
        }
    }
}