//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://ec.europa.eu/tracesnt/certificate/ched/alert/noncompliance/v01")]
    public partial class ReasonsForRefusalType
    {
        private CodeType refusalReasonCodeField;
        private ConcernedSPSConsignmentItemType[] concernedSPSConsignmentItemField;
        private SPSClassificationType[] applicableSPSClassificationField;
        private SPSNoteType[] includedSPSNoteField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CodeType RefusalReasonCode
        {
            get
            {
                return this.refusalReasonCodeField;
            }

            set
            {
                this.refusalReasonCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConcernedSPSConsignmentItem", Order = 1)]
        public ConcernedSPSConsignmentItemType[] ConcernedSPSConsignmentItem
        {
            get
            {
                return this.concernedSPSConsignmentItemField;
            }

            set
            {
                this.concernedSPSConsignmentItemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ApplicableSPSClassification", Order = 2)]
        public SPSClassificationType[] ApplicableSPSClassification
        {
            get
            {
                return this.applicableSPSClassificationField;
            }

            set
            {
                this.applicableSPSClassificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("IncludedSPSNote", Order = 3)]
        public SPSNoteType[] IncludedSPSNote
        {
            get
            {
                return this.includedSPSNoteField;
            }

            set
            {
                this.includedSPSNoteField = value;
            }
        }
    }
}