//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:21" + "")]
    public partial class SPSAddressType
    {
        private CodeType postcodeCodeField;
        private TextType lineOneField;
        private TextType lineTwoField;
        private TextType lineThreeField;
        private TextType lineFourField;
        private TextType lineFiveField;
        private TextType cityNameField;
        private IDType countryIDField;
        private AddressTypeCodeType typeCodeField;
        private TextType countryNameField;
        private IDType countrySubDivisionIDField;
        private TextType countrySubDivisionNameField;
        private IDType cityIDField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public CodeType PostcodeCode
        {
            get
            {
                return this.postcodeCodeField;
            }

            set
            {
                this.postcodeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public TextType LineOne
        {
            get
            {
                return this.lineOneField;
            }

            set
            {
                this.lineOneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public TextType LineTwo
        {
            get
            {
                return this.lineTwoField;
            }

            set
            {
                this.lineTwoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 3)]
        public TextType LineThree
        {
            get
            {
                return this.lineThreeField;
            }

            set
            {
                this.lineThreeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public TextType LineFour
        {
            get
            {
                return this.lineFourField;
            }

            set
            {
                this.lineFourField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 5)]
        public TextType LineFive
        {
            get
            {
                return this.lineFiveField;
            }

            set
            {
                this.lineFiveField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public TextType CityName
        {
            get
            {
                return this.cityNameField;
            }

            set
            {
                this.cityNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 7)]
        public IDType CountryID
        {
            get
            {
                return this.countryIDField;
            }

            set
            {
                this.countryIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 8)]
        public AddressTypeCodeType TypeCode
        {
            get
            {
                return this.typeCodeField;
            }

            set
            {
                this.typeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 9)]
        public TextType CountryName
        {
            get
            {
                return this.countryNameField;
            }

            set
            {
                this.countryNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 10)]
        public IDType CountrySubDivisionID
        {
            get
            {
                return this.countrySubDivisionIDField;
            }

            set
            {
                this.countrySubDivisionIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 11)]
        public TextType CountrySubDivisionName
        {
            get
            {
                return this.countrySubDivisionNameField;
            }

            set
            {
                this.countrySubDivisionNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 12)]
        public IDType CityID
        {
            get
            {
                return this.cityIDField;
            }

            set
            {
                this.cityIDField = value;
            }
        }
    }
}