//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:un:unece:uncefact:data:standard:SPSCertificate:17")]
    public partial class SPSCertificateType
    {
        private SPSExchangedDocumentType sPSExchangedDocumentField;
        private SPSConsignmentType sPSConsignmentField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public SPSExchangedDocumentType SPSExchangedDocument
        {
            get
            {
                return this.sPSExchangedDocumentField;
            }

            set
            {
                this.sPSExchangedDocumentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public SPSConsignmentType SPSConsignment
        {
            get
            {
                return this.sPSConsignmentField;
            }

            set
            {
                this.sPSConsignmentField = value;
            }
        }
    }
}