//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:un:unece:uncefact:data:standard:ReusableAggregateBusinessInformationEntity:21" + "")]
    public partial class SPSPartyType
    {
        private IDType idField;
        private TextType nameField;
        private PartyRoleCodeType roleCodeField;
        private CodeType[] typeCodeField;
        private SPSAddressType specifiedSPSAddressField;
        private SPSContactType[] definedSPSContactField;
        private SPSPersonType specifiedSPSPersonField;
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public IDType ID
        {
            get
            {
                return this.idField;
            }

            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public TextType Name
        {
            get
            {
                return this.nameField;
            }

            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public PartyRoleCodeType RoleCode
        {
            get
            {
                return this.roleCodeField;
            }

            set
            {
                this.roleCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TypeCode", Order = 3)]
        public CodeType[] TypeCode
        {
            get
            {
                return this.typeCodeField;
            }

            set
            {
                this.typeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public SPSAddressType SpecifiedSPSAddress
        {
            get
            {
                return this.specifiedSPSAddressField;
            }

            set
            {
                this.specifiedSPSAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DefinedSPSContact", Order = 5)]
        public SPSContactType[] DefinedSPSContact
        {
            get
            {
                return this.definedSPSContactField;
            }

            set
            {
                this.definedSPSContactField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 6)]
        public SPSPersonType SpecifiedSPSPerson
        {
            get
            {
                return this.specifiedSPSPersonField;
            }

            set
            {
                this.specifiedSPSPersonField = value;
            }
        }
    }
}