//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/base/v03")]
    public enum SupplementaryQuantityTypeUnitCode
    {
        /// <remarks/>
        LTR,
        /// <remarks/>
        MTQ,
        /// <remarks/>
        H87,
        /// <remarks/>
        LEF,
        /// <remarks/>
        STW,
        /// <remarks/>
        BG,
        /// <remarks/>
        BL,
        /// <remarks/>
        BX,
        /// <remarks/>
        MTK,
        /// <remarks/>
        BY,
        /// <remarks/>
        VR,
        /// <remarks/>
        CA,
        /// <remarks/>
        CI,
        /// <remarks/>
        CT,
        /// <remarks/>
        CS,
        /// <remarks/>
        CK,
        /// <remarks/>
        CF,
        /// <remarks/>
        CN,
        /// <remarks/>
        CR,
        /// <remarks/>
        DR,
        /// <remarks/>
        FB,
        /// <remarks/>
        JR,
        /// <remarks/>
        PK,
        /// <remarks/>
        PL,
        /// <remarks/>
        PX,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8C")]
        Item8C,
        /// <remarks/>
        SA,
        /// <remarks/>
        SH,
        /// <remarks/>
        SI,
        /// <remarks/>
        ST,
        /// <remarks/>
        TK,
        /// <remarks/>
        TY,
        /// <remarks/>
        TT,
        /// <remarks/>
        PT,
        /// <remarks/>
        DT,
        /// <remarks/>
        TU,
        /// <remarks/>
        VI,
        /// <remarks/>
        QP,
        /// <remarks/>
        QQ,
        /// <remarks/>
        BA,
        /// <remarks/>
        BE,
        /// <remarks/>
        BH,
        /// <remarks/>
        BI,
        /// <remarks/>
        QH,
        /// <remarks/>
        QJ,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("24")]
        Item24,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("8B")]
        Item8B,
        /// <remarks/>
        XD,
        /// <remarks/>
        RT,
        /// <remarks/>
        PA,
        /// <remarks/>
        PO,
        /// <remarks/>
        PJ,
        /// <remarks/>
        LE,
        /// <remarks/>
        GR,
        /// <remarks/>
        WA,
        /// <remarks/>
        DU,
        /// <remarks/>
        PB,
    }
}