//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices.CertexServices
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://ec.europa.eu/sanco/tracesnt/customs_certex/base/v03")]
    public partial class SWSupportingWRoundingDocumentTypeQuantity
    {
        private decimal technicalRoundingQuantityField;
        private bool technicalRoundingQuantityFieldSpecified;
        private decimal valueField;
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TechnicalRoundingQuantity
        {
            get
            {
                return this.technicalRoundingQuantityField;
            }

            set
            {
                this.technicalRoundingQuantityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TechnicalRoundingQuantitySpecified
        {
            get
            {
                return this.technicalRoundingQuantityFieldSpecified;
            }

            set
            {
                this.technicalRoundingQuantityFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value
        {
            get
            {
                return this.valueField;
            }

            set
            {
                this.valueField = value;
            }
        }
    }
}