//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace TracesNT.WebServices
{
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaxonReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassificationTreeDescription))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OperatorActivityTypeReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MetaCountryGroupReference))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "urn:un:unece:uncefact:data:standard:UnqualifiedDataType:21")]
    public partial class TextType
    {
        private string languageIDField;
        private string languageLocaleIDField;
        private string valueField;
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string languageID
        {
            get
            {
                return this.languageIDField;
            }

            set
            {
                this.languageIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType = "token")]
        public string languageLocaleID
        {
            get
            {
                return this.languageLocaleIDField;
            }

            set
            {
                this.languageLocaleIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }

            set
            {
                this.valueField = value;
            }
        }
    }
}